In [1]:
import csv
import xlrd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


## CPS Historical Migration/Geographic Mobility Tables##

https://www.census.gov/data/tables/time-series/demo/geographic-mobility/historic.html

    Note:
        As of November 2018, these historical tables include corrections to errors that were discovered.
        Please replace any previously downloaded historical tables.
    Action:
        load in tables
        brief pre-exploration overview analysis (6 total)

In [113]:
# Table A-1. Annual Geographical Mobility Rates, By Type of Movement: 2018
annual_geographical_mobility_rates_type_movement = pd.read_excel( '../../data/cps-historical-migration-geographic-mobility/tab-a-1.xls' )

# # Table A-2. Annual Inmigration, Outmigration, Net Migration, and Movers from Abroad for Regions: 2018
annual_inmigration_outmigration_net_migration__movers_from_abroad_for_regions = pd.read_excel( '../../data/cps-historical-migration-geographic-mobility/tab-a-2.xls' )

# # Table A-3. Inmigration, Outmigration, and Net Migration by Metropolitan Status: 2018
inmigration_outmigration__net_migration_metropolitan_status = pd.read_excel( '../../data/cps-historical-migration-geographic-mobility/tab-a-3.xls' )

# # Table A-4. Geographical Mobility by Tenure: 2018
geographical_mobility_by_tenure = pd.read_excel( '../../data/cps-historical-migration-geographic-mobility/tab-a-4.xls' )

# # Table A-5. Reason for Move (Specific Categories): 2018
reason_for_move_specific_categories = pd.read_excel( '../../data/cps-historical-migration-geographic-mobility/tab-a-5.xls' )

# # Table A-6. Distance of Intercounty Move: 2018
distance_of_intercounty_move = pd.read_excel( '../../data/cps-historical-migration-geographic-mobility/tab-a-6.xls' )

In [114]:
'''annual_geographical_mobility_rates_type_movement'''

# print( annual_geographical_mobility_rates_type_movement.info() )
# annual_geographical_mobility_rates_type_movement.sample( 3 ) 
pass

***annual_geographical_mobility_rates_type_movement***
- notes:
    - seems to cover back to 1947
    - needs to be cleaned , pd does not naturally detect formatting 
        - top and bottom
    - varying length of information
        - count (column(s))
            - 154 (0) , 138 (4, 6) , 137 (1, 2, 3, 5, 7, 8, 9)
        - information length is most likely <= 137

In [115]:
'''annual_inmigration_outmigration_net_migration__movers_from_abroad_for_regions'''

# print( annual_inmigration_outmigration_net_migration__movers_from_abroad_for_regions.info() )
annual_inmigration_outmigration_net_migration__movers_from_abroad_for_regions #.sample( 3 )

,Table with row headers in column A and column headers in row 5.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,"Table A-2. Annual Inmigration, Outmigration, ...",NaN,NaN,NaN,NaN
1,(Numbers in thousands.),NaN,NaN,NaN,NaN
2,(leading dot indicates sub-part),NaN,NaN,NaN,NaN
3,Mobility period and type of migration,Northeast,Midwest,South,West
4,NaN,NaN,NaN,NaN,NaN
5,2017-2018,NaN,NaN,NaN,NaN
6,.Inmigrants,243,518,1227,566
7,.Outmigrants,595,555,714,689
8,.Net internal migration,-352*,-38,512*,-122
9,.Movers from abroad,229,156,446,335
10,.Net migration (including abroad),-124,118,959*,212*
11,NaN,NaN,NaN,NaN,NaN
12,2016-2017,NaN,NaN,NaN,NaN
13,.Inmigrants,405,544,1050,696
14,.Outmigrants,606,569,1006,515
15,.Net internal migration,-200*,-25,44,181*
16,.Movers from abroad,223,150,504,379
17,.Net migration (including abroad),23,125,548*,560*
18,NaN,NaN,NaN,NaN,NaN
19,2015-2016,NaN,NaN,NaN,NaN
20,.Inmigrants,337,442,940,719
21,.Outmigrants,553,513,901,472
22,.Net internal migration,-216*,-71,39,247*
23,.Movers from abroad,266,163,497,355
24,.Net migration (including abroad),50,92,536*,602*
25,NaN,NaN,NaN,NaN,NaN
26,2014-2015,NaN,NaN,NaN,NaN
27,.Inmigrants,403,463,1010,562
28,.Outmigrants,504,575,740,620
29,.Net internal migration,-101*,-112*,271*,-57
...,...,...,...,...,...
272,NaN,NaN,NaN,NaN,NaN
273,1982-1983,NaN,NaN,NaN,NaN
274,.Inmigrants,439,661,1211,880
275,.Outmigrants,625,947,973,645
276,.Net internal migration,-186*,-286*,238*,235*
277,.Movers from abroad,192,149,323,315
278,.Net migration (including abroad),6,-137,561*,550*
279,NaN,NaN,NaN,NaN,NaN
280,1981-1982,NaN,NaN,NaN,NaN
281,.Inmigrants,473,793,1482,931
282,.Outmigrants,685,1163,1012,819
283,.Net internal migration,-212*,-370*,470*,112
284,.Movers from abroad,229,134,401,324
285,.Net migration (including abroad),17,-236*,871*,436*
286,NaN,NaN,NaN,NaN,NaN
287,1980-1981,NaN,NaN,NaN,NaN
288,.Inmigrants,464,650,1377,871
289,.Outmigrants,706,1056,890,710
290,.Net internal migration,-242*,-406*,487*,161
291,.Movers from abroad,207,180,412,514
292,.Net migration (including abroad),-35,-226*,899*,675*
293,Footnotes:,NaN,NaN,NaN,NaN
294,* Net flow significantly different from zero a...,NaN,NaN,NaN,NaN
295,1/ The 2014 CPS ASEC included redesigned quest...,NaN,NaN,NaN,NaN
296,2/ Population controls consistent with 2010 Ce...,NaN,NaN,NaN,NaN
297,3/ Population controls consistent with 2000 Ce...,NaN,NaN,NaN,NaN
298,4/ SCHIP sample: poulation controls consistent...,NaN,NaN,NaN,NaN
299,5/ Population controls consistent with 1990 Ce...,NaN,NaN,NaN,NaN
300,6/ Regional 1-year migration data are not avai...,NaN,NaN,NaN,NaN
301,"Source: U.S. Census Bureau, Current Populatio...",NaN,NaN,NaN,NaN

***annual_inmigration_outmigration_net_migration__movers_from_abroad_for_regions***
- notes:
    - seems to cover back to 1980
    - needs to be cleaned , pd does not naturally detect formatting 
        - top and bottom

In [116]:
'''inmigration_outmigration__net_migration_metropolitan_status'''

# print( inmigration_outmigration__net_migration_metropolitan_status.info() )
inmigration_outmigration__net_migration_metropolitan_status # .sample( 3 )
# pass

,Table with row headers in column A and column headers in row 5.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,"Table A-3. Inmigration, Outmigration, and Net...",NaN,NaN,NaN,NaN,NaN
1,(Numbers in thousands.),NaN,NaN,NaN,NaN,NaN
2,(Leading dots indicate sub-parts),NaN,NaN,NaN,NaN,NaN
3,Mobility period and Metropolitan status,Inmigrants,Outmigrants,Net domestic migration,Movers from abroad,Net migration including movers from abroad
4,(leading dots indicate sub-parts),NaN,NaN,NaN,NaN,NaN
5,2017-2018,NaN,NaN,NaN,NaN,NaN
6,.Metropolitan areas,1073,991,82,1121,"1,203*"
7,..Principal cities,3180,5456,-2277*,569,"-1,707*"
8,..Balances of metropolitan areas/8,5570,3211,2358*,553,"2,911*"
9,.Nonmetropolitan areas,991,1073,-82,44,-38
10,NaN,NaN,NaN,NaN,NaN,NaN
11,2016-2017,NaN,NaN,NaN,NaN,NaN
12,.Metropolitan areas,1008,1004,4,1204,"1,208*"
13,..Principal cities,3196,5515,"-2,319*",626,"-1,693*"
14,..Suburbs,5646,3323,"2,323*",578,"2,901*"
15,.Nonmetropolitan areas,1004,1008,-4,51,47
16,NaN,NaN,NaN,NaN,NaN,NaN
17,2015-2016,NaN,NaN,NaN,NaN,NaN
18,.Metropolitan areas,1221,1025,196*,1201,"1,397*"
19,..Principal cities,3372,5381,"-2,009*",631,"-1,378*"
20,..Suburbs,5617,3411,"2,206*",570,"2,776*"
21,.Nonmetropolitan areas,1025,1221,-197*,80,-117
22,NaN,NaN,NaN,NaN,NaN,NaN
23,2014-2015/1,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN
25,"2013-2014 (98,000 address file)/2",NaN,NaN,NaN,NaN,NaN
26,.Metropolitan areas,1486,1035,451*,1095,"1,546*"
27,..Principal cities,3455,5198,"-1,744*",515,"-1,229*"
28,..Suburbs,5487,3292,"2,195*",580,"2,775*"
29,.Nonmetropolitan areas,1035,1486,-451*,38,-413*
...,...,...,...,...,...,...
182,.Metropolitan areas,1820,1651,169,1021,"1,190*"
183,..Central cities,3461,6084,"-2,623*",576,"-2,047*"
184,..Suburbs,6421,3629,"2,792*",445,"3,237*"
185,.Nonmetropolitan areas,1651,1820,-169,179,10
186,NaN,NaN,NaN,NaN,NaN,NaN
187,1986-1987,NaN,NaN,NaN,NaN,NaN
188,.Metropolitan areas,2148,1660,488*,1033,"1,521*"
189,..Central cities,4342,6022,"-1,680*",609,"-1,071*"
190,..Suburbs,6378,4211,"2,167*",424,"2,591*"
191,.Nonmetropolitan areas,1660,2148,-488*,110,-378*
192,NaN,NaN,NaN,NaN,NaN,NaN
193,1985-1986,NaN,NaN,NaN,NaN,NaN
194,.Metropolitan areas,2034,1731,303*,1082,"1,385*"
195,..Central cities,4222,5802,"-1,580*",580,"-1,000*"
196,..Suburbs,6168,4285,"1,883*",502,"2,385*"
197,.Nonmetropolitan areas,1731,2034,-303*,118,-185
198,Footnotes:,NaN,NaN,NaN,NaN,NaN
199,* Net flow significantly different from zero a...,NaN,NaN,NaN,NaN,NaN
200,1/ Metropolitan mobility data are not availabl...,NaN,NaN,NaN,NaN,NaN
201,2/ The 2014 CPS ASEC included redesigned quest...,NaN,NaN,NaN,NaN,NaN
202,3/ Population controls consistent with 2010 Ce...,NaN,NaN,NaN,NaN,NaN
203,4/ Population controls consistent with 2000 Ce...,NaN,NaN,NaN,NaN,NaN
204,5/ Metropolitan mobility data are not availabl...,NaN,NaN,NaN,NaN,NaN
205,6/ SCHIP sample: population controls consisten...,NaN,NaN,NaN,NaN,NaN
206,7/ 1-year metropolitan migration data are not ...,NaN,NaN,NaN,NaN,NaN
207,"8/ Beginning in 2018, the description of locat...",NaN,NaN,NaN,NaN,NaN
208,Footnotes continued:,NaN,NaN,NaN,NaN,NaN
209,Note: 1996-97 data are for MAs as defined in 1...,NaN,NaN,NaN,NaN,NaN
210,Note: Data for 1985-1986 and 1986-1987 are cor...,NaN,NaN,NaN,NaN,NaN
211,"Source: U.S. Census Bureau, Current Populatio...",NaN,NaN,NaN,NaN,NaN

***inmigration_outmigration__net_migration_metropolitan_status***
- notes:
    - seems to cover back to 1985
    - needs to be cleaned , pd does not naturally detect formatting 
        - top and bottom

In [117]:
'''geographical_mobility_by_tenure'''

# print( geographical_mobility_by_tenure.info() )
geographical_mobility_by_tenure #.sample( 3 )
# pass

,"Table with row headers in column A and column headers in rows 5 through 7. Numbers start in row 10, percentages start in row 184, and frequency distributions start in row 358.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Table A-4. Geographical Mobility by Tenure: 1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(Numbers in thousands.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(leading dot indicates sub-part),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mobility period and Tenure,Total persons,Same house (non-movers),Total movers,Different house in the United States,NaN,NaN,NaN,NaN,Movers from abroad
4,NaN,NaN,NaN,NaN,Total,Same county,Different county,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,Total,Same State,Different State,NaN
6,NUMBERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2017-2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,".Total, 1 year and over",319319,286967,32352,31186,19852,11334,6496,4838,1165
10,..In owner-occupied units,212827,201902,10925,10645,6650,3994,2415,1579,280
11,..In renter-occupied units,106493,85066,21427,20542,13202,7340,4081,3259,885
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2016-2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,".Total, 1 year and over",316550,281647,34902,33647,21614,12033,6668,5366,1255
15,..In owner-occupied units,208569,197067,11502,11208,6910,4298,2477,1821,294
16,..In renter-occupied units,107980,84580,23400,22440,14704,7736,4191,3545,961
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2015-2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,".Total, 1 year and over",314992,279854,35138,33857,21588,12269,7501,4768,1281
20,..In owner-occupied units,206767,196431,10336,10135,6278,3857,2608,1249,201
21,..In renter-occupied units,108224,83423,24801,23721,15310,8411,4893,3519,1080
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2014-2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,".Total, 1 year and over",312295,275971,36324,34651,22905,11746,6653,5093,1673
25,..In owner-occupied units,204646,194195,10452,10157,6478,3679,2086,1594,294
26,..In renter-occupied units,107649,81777,25872,24493,16426,8067,4567,3499,1379
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,"2013-2014 (98,000 address file)/1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,".Total, 1 year and over",309601,273920,35681,34548,23436,11112,6446,4666,1133
...,...,...,...,...,...,...,...,...,...,...
505,..In owner-occupied units,66.9,73.7,34.6,34.7,32.1,39.3,39,39.5,29.6
506,..In renter-occupied units,33.1,26.3,65.4,65.3,67.9,60.7,61,60.5,70.4
507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
508,1990-1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
509,".Total, 1 year and over",100,100,100,100,100,100,100,100,100
510,..In owner-occupied units,67,73.6,34.8,35.3,32.6,39.8,40,39.4,20.1
511,..In renter-occupied units,33,26.4,65.2,64.7,67.4,60.2,60,60.6,79.8
512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513,1989-1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
514,".Total, 1 year and over",100,100,100,100,100,100,100,100,100
515,..In owner-occupied units,67.2,74.4,34.7,35.2,32.9,38.8,40.6,36.9,22.2
516,..In renter-occupied units,32.8,25.6,65.3,64.9,67.1,61.2,59.4,63.1,77.8
517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,1988-1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
519,".Total, 1 year and over",100,100,100,100,100,100,100,100,100
520,..In owner-occupied units,67.6,74.6,35.5,35.8,33,40.7,43.5,37.5,26.4
521,..In renter-occupied units,32.4,25.4,64.5,64.2,67,59.3,56.5,62.5,73.5
522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,1987-1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
524,".Total, 1 year and over",100,100,100,100,100,100,100,100,100
525,..In owner-occupied units,67.8,74.6,36.1,36.4,34.9,38.9,42.4,35,27.9
526,..In renter-occupied units,32.2,25.4,63.9,63.6,65.1,61.1,57.6,64.9,72
527,Footnotes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528,1/ The 2014 CPS ASEC included redesigned quest...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
529,2/ Population controls consistent with 2010 Ce...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,3/ Population controls consistent with 2000 Ce...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,4/ SCHIP sample: poulation controls consistent...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,5/ Population controls consistent with 1990 Ce...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533,6/ 1-year migration data by tenure are not ava...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
534,"Source: U.S. Census Bureau, Current Populatio...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

***geographical_mobility_by_tenure***
- notes:
    - seems to cover back to 1987
    - needs to be cleaned , pd does not naturally detect formatting 
        - top and bottom

In [7]:
'''reason_for_move_specific_categories'''

# print( reason_for_move_specific_categories.info() )
# reason_for_move_specific_categories.sample( 3 )
pass

***reason_for_move_specific_categories***
- notes:
    - seems to cover back to 1998
    - needs to be cleaned , pd does not naturally detect formatting 
        - top and bottom

In [8]:
# distance_of_intercounty_move
# print( distance_of_intercounty_move.info() )
# distance_of_intercounty_move.sample( 3 )
pass

***distance_of_intercounty_move***
- notes:
    - seems to cover back to 2002
    - needs to be cleaned , pd does not naturally detect formatting 
        - top and bottom

## Aggregate Initial Notes
- ***Dates***
    - first recording year varies by up to 55 years 

| first recording year | dataset |
|- - - -|- - - -|
| 1947 | annual_geographical_mobility_rates_type_movement |
|- - - -|- - - -|
| 1980 | annual_inmigration_outmigration_net_migration__movers_from_abroad_for_regions |
|- - - -|- - - -|
| 1985 | inmigration_outmigration__net_migration_metropolitan_status |
|- - - -|- - - -|
| 1987 | inmigration_outmigration__net_migration_metropolitan_status |
|- - - -|- - - -|
| 1998 | reason_for_move_specific_categories |
|- - - -|- - - -|
| 2002 | distance_of_intercounty_move |

- ***format***
    - first rows of each file seem to serve as information , actual tables start near end of .head()
    - ending rows of each file seem to serve as annotation and disclaimer
- ***actions***:
    - walk though one table at a time
    - let's start with dropping NaN clustered rows

In [9]:
# copy dataframe , generalize name
df = annual_geographical_mobility_rates_type_movement.copy()
# drop columns without any non-NaN values
df = df.dropna(thresh= ( 1 ) )
# return the dataframe to see results
# df
df.sample(7)

,Table with row headers in column A and column headers in rows 5 through 7.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
106,2007-2008,100,88.1,11.9,11.5,7.8,3.7,2.1,1.6,0.4
38,1995-1996,260406,217868,42537,41176,26696,14480,8009,6471,1361
15,2011-2012,304924,268436,36488,35334,23493,11842,6782,5059,1154
71,1961-1962,179663,144445,35218,34364,23341,11023,5461,5562,854
100,2010-2011 (2010 controls)/2,100,88.4,11.6,11.2,7.7,3.5,1.9,1.6,0.4
111,2003-2004,100,86.3,13.7,13.3,7.9,5.3,2.8,2.6,0.4
93,2016-2017,100,89,11,10.6,6.8,3.8,2.1,1.7,0.4

- ***notes:***
    - 156 rows remain
    - some column names in row 3 , some column names in row 4 , some column names in row 5
        row 3 = 6 column names
            columns = 0 , 1 , 2 , 3 , 4 , 9
        row 4 = 2 column names
            columns = 5 , 6
        row 5 = 2 column names
            columns = 7 , 8
    - row 4 column 4 and row 5 column 6 contain 'Total'
        not obvious what this is
        but it is not the column name in either case
        in both cases , the column name is one row higher in the same column
    - rows 173 - 185 contain only 1 NaN value
- ***actions:***
    - drop all rows without 2 or more non-NaN values
    - merge rows 3 , 4 , and 5 
        taking out 'Total'

In [10]:
# rename dataframe
df = annual_geographical_mobility_rates_type_movement.copy()

# drop columns with less than 2 non-NaN values
df = df.dropna( thresh= ( 2 ) )

# collect column names as pd series
col_names_0to4_9 = df.iloc[ 0 ]
col_names_5to6 = df.iloc[ 1 ]
col_names7to8 = df.iloc[ 2 ]

# initialize list of column names 
column_names = [ column_name for column_name in col_names_0to4_9 ]
# ^because it is the base list , list is first row of column names

# set index count to -1 so column 0 == column 0  
_ = -1

# replace items 5 and 6 in column_names with column names 5 and 6
for column_name in col_names_5to6:
    _ += 1
    # column_name is string (nan instances = float) and name is not 'Total'   
    if isinstance( column_name , str ) and column_name != 'Total':
        # column_name is aligned to replace a nan         
        if str( column_names[ _ ] ) == 'nan':
            # replace item in column_names with column_name             
            column_names[ _ ] = column_name

# 0 == 0
_ = -1

# replace items 7 and 8 in column_names with column names 7 and 8
for column_name in col_names7to8:
    _ += 1
    # column_name is string (nan instances = float) and name is not 'Total'   
    if isinstance( column_name , str ) and column_name != 'Total':
        # column_name is aligned to replace a nan         
        if str( column_names[ _ ] ) == 'nan':
            # replace item in column_names with column_name             
            column_names[ _ ] = column_name

# (re)set column names
df.columns = column_names

# drop rows used to extract column names
df = df[3:]

# reset dataframe index
df = df.reset_index( drop=True ) 

# let's see
df #.head(10)

,Mobility period,"Total, 1 year old and over",Same residence (non-movers),Total movers,Different residence in the United States,Same county,Different county,Same state,Different state,Movers from abroad
0,2017-2018,319319,286967,32352,31186,19852,11334,6496,4838,1165
1,2016-2017,316550,281647,34902,33647,21614,12033,6668,5366,1255
2,2015-2016,314992,279854,35138,33857,21588,12269,7501,4768,1281
3,2014-2015,312295,275971,36324,34651,22905,11746,6653,5093,1673
4,"2013-2014 (98,000 address file)/1",309601,273920,35681,34548,23436,11112,6446,4666,1133
5,2012-2013,307243,271325,35918,34882,23150,11731,6961,4770,1036
6,2011-2012,304924,268436,36488,35334,23493,11842,6782,5059,1154
7,2010-2011 (2010 controls)/2,302640,267602,35038,33953,23330,10623,5868,4756,1084
8,2010-2011 (2000 controls)/3,302005,266930,35075,34016,23325,10691,5912,4779,1058
9,2009-2010 (2010 controls)/2,300419,262975,37445,36459,25910,10549,6227,4323,985
10,2009-2010 (2000 controls)/3,300074,262534,37540,36594,26017,10577,6252,4326,946
11,2008-2009,297182,260077,37105,36017,24984,11034,6374,4660,1087
12,2007-2008,294851,259685,35167,34022,23013,11009,6282,4728,1145
13,2006-2007,292749,254068,38681,37490,25192,12298,7436,4862,1191
14,2005-2006,289781,249945,39837,38541,24851,13690,8010,5679,1296
15,2004-2005/4,287148,247261,39888,38023,22736,15287,7847,7441,1865
16,2003-2004,284367,245372,38995,37723,22551,15172,7842,7330,1272
17,2002-2003,282556,242463,40093,38824,23468,15356,7728,7628,1269
18,2001-2002,278160,237049,41111,39548,23712,15836,8066,7770,1563
19,2000-2001 (2000 controls)/3,275611,236605,39007,37251,21918,15333,7550,7783,1756
20,"2000-2001 (SCHIP, 2000 controls)/5",275611,235726,39885,38133,22774,15360,7778,7582,1752
21,2000-2001 (1990 controls)/6,272671,234029,38641,36993,21783,15210,7531,7679,1648
22,1999-2000,270219,226831,43388,41642,24399,17242,8814,8428,1746
23,1998-1999,267933,225297,42636,41207,25268,15939,8423,7516,1429
24,1997-1998,265209,222702,42507,41304,27082,14222,7867,6355,1203
25,1996-1997,262976,219585,43391,42088,27740,14348,7960,6389,1303
26,1995-1996,260406,217868,42537,41176,26696,14480,8009,6471,1361
27,1994-1995,258248,215931,42317,41539,27908,13631,7888,5743,778
28,1993-1994,255774,212939,42835,41590,26638,14952,8226,6726,1245
29,1992-1993 (1990 controls)/6,252799,209700,43099,41704,26932,14772,7855,6916,1395
...,...,...,...,...,...,...,...,...,...,...
106,1984-1985,100,79.8,20.2,19.6,13.1,6.5,3.5,3,0.6
107,1983-1984,100,82.7,17.3,16.8,10.4,6.4,3.6,2.8,0.5
108,1982-1983,100,83.4,16.6,16.1,10.1,6,3.3,2.7,0.4
109,1981-1982,100,83,17,16.6,10.3,6.2,3.3,3,0.5
110,1980-1981,100,82.8,17.2,16.6,10.4,6.2,3.4,2.8,0.6
111,1975-1976/8,100,82.3,17.7,17.1,10.8,6.4,3.4,3,0.6
112,1970-1971/8,100,81.3,18.7,17.9,11.4,6.5,3.1,3.4,0.8
113,1969-1970,100,80.9,19.1,18.4,11.7,6.7,3.1,3.6,0.8
114,1968-1969,100,81,19,18.3,11.7,6.6,3.2,3.4,0.7
115,1967-1968,100,80.5,19.5,18.8,11.8,7,3.4,3.6,0.7
116,1966-1967,100,81,19,18.3,11.6,6.7,3.3,3.4,0.7
117,1965-1966,100,80.2,19.8,19.3,12.7,6.6,3.3,3.3,0.5
118,1964-1965,100,79.3,20.7,20.1,13.4,6.8,3.5,3.3,0.5
119,1963-1964,100,79.9,20.1,19.6,13,6.6,3.3,3.3,0.5
120,1962-1963,100,80,20,19.4,12.6,6.8,3.1,3.6,0.6
121,1961-1962,100,80.4,19.6,19.1,13,6.1,3,3.1,0.5
122,1960-1961,100,79.4,20.6,20,13.7,6.3,3.1,3.2,0.6
123,1959-1960,100,80.1,19.9,19.4,12.9,6.4,3.3,3.2,0.5
124,1958-1959,100,80.3,19.7,19.2,13.1,6.1,3.2,3,0.5
125,1957-1958,100,79.7,20.3,19.8,13.1,6.7,3.4,3.3,0.5
126,1956-1957,100,80.1,19.9,19.4,13.1,6.2,3.2,3.1,0.5
127,1955-1956,100,78.9,21.1,20.5,13.7,6.8,3.6,3.1,0.6
128,1954-1955,100,79.6,20.4,19.9,13.3,6.6,3.5,3.1,0.6
129,1953-1954,100,80.7,19.3,18.6,12.2,6.4,3.2,3.2,0.6
130,1952-1953,100,79.4,20.6,20.1,13.5,6.6,3,3.6,0.5
131,1951-1952,100,79.7,20.3,19.8,13.2,6.6,3.2,3.4,0.4
132,1950-1951,100,78.8,21.2,21,13.9,7.1,3.6,3.5,0.2
133,1949-1950,100,80.9,19.1,18.7,13.1,5.6,3,2.6,0.3
134,1948-1949,100,80.8,19.2,18.8,13,5.8,2.8,3,0.3
135,1947-1948,100,79.8,20.2,19.9,13.6,6.4,3.3,3.1,0.3

- ***as of now***:
    - removed rows with NaN values
    - extracted, sorted, and set column names
- ***next (action)***:
    - we need to clean up the 'Mobility period' column
        - samples from current:
            - 2017-2018
            - 2013-2014 (98,000 address file)/1
            - 2011-2012
            - 2010-2011 (2010 controls)/2
            - 2000-2001 (SCHIP, 2000 controls)/5
            - 1970-1971/8
        - what we want:
            - 2018 << 2017-2018
            - 2014 << 2013-2014 (98,000 address file)/1
                requires further investigation
            - 2012 << 2011-2012
            - 2011 << 2010-2011 (2010 controls)/2
                requires further investigation
            - 2001 << 2000-2001 (SCHIP, 2000 controls)/5
                requires further investigation
            - 1971 << 1970-1971/8

In [11]:
# examine data in 'Mobility period'
# _ = 0
# for instance in df[ 'Mobility period' ]:
#     # print( _ , instance )
#     _ += 1
    
# selected outputs 
'''
# non-uniform , non-repeated
    3 2014-2015
    4 2013-2014 (98,000 address file)/1
    5 2012-2013
    
# repeats w/ controls , no uniform representation
    6 2011-2012
    7 2010-2011 (2010 controls)/2
    8 2010-2011 (2000 controls)/3
    9 2009-2010 (2010 controls)/2
    10 2009-2010 (2000 controls)/3
    11 2008-2009

    18 2001-2002
    19 2000-2001 (2000 controls)/3
    20 2000-2001 (SCHIP, 2000 controls)/5
    21 2000-2001 (1990 controls)/6
    22 1999-2000
    
    28 1993-1994
    29 1992-1993 (1990 controls)/6
    30 1992-1993 (1980 controls)/7
    31 1991-1992
    
# lack of info from 70s 
    41 1981-1982
    42 1980-1981
    43 1975-1976/8
    44 1970-1971/8
    45 1969-1970
    46 1968-1969
    47 1967-1968
    
# in chronological order until row 68 (then repeats)
    66 1948-1949
    67 1947-1948
    68 2017-2018
    69 2016-2017
'''

# make sure rows 0-67 are the same as 68-135
# new copy
copy_mobility_period = df[ 'Mobility period' ].copy()

# # index first half
# for _ in range( len( copy_mobility_period[ 0:68 ] ) ):
#     # print each row in first half with corresponding row in 2nd half
#     print( copy_mobility_period[ _ ] + '  |  ' + copy_mobility_period[ 68 + _ ])
df

,Mobility period,"Total, 1 year old and over",Same residence (non-movers),Total movers,Different residence in the United States,Same county,Different county,Same state,Different state,Movers from abroad
0,2017-2018,319319,286967,32352,31186,19852,11334,6496,4838,1165
1,2016-2017,316550,281647,34902,33647,21614,12033,6668,5366,1255
2,2015-2016,314992,279854,35138,33857,21588,12269,7501,4768,1281
3,2014-2015,312295,275971,36324,34651,22905,11746,6653,5093,1673
4,"2013-2014 (98,000 address file)/1",309601,273920,35681,34548,23436,11112,6446,4666,1133
5,2012-2013,307243,271325,35918,34882,23150,11731,6961,4770,1036
6,2011-2012,304924,268436,36488,35334,23493,11842,6782,5059,1154
7,2010-2011 (2010 controls)/2,302640,267602,35038,33953,23330,10623,5868,4756,1084
8,2010-2011 (2000 controls)/3,302005,266930,35075,34016,23325,10691,5912,4779,1058
9,2009-2010 (2010 controls)/2,300419,262975,37445,36459,25910,10549,6227,4323,985
10,2009-2010 (2000 controls)/3,300074,262534,37540,36594,26017,10577,6252,4326,946
11,2008-2009,297182,260077,37105,36017,24984,11034,6374,4660,1087
12,2007-2008,294851,259685,35167,34022,23013,11009,6282,4728,1145
13,2006-2007,292749,254068,38681,37490,25192,12298,7436,4862,1191
14,2005-2006,289781,249945,39837,38541,24851,13690,8010,5679,1296
15,2004-2005/4,287148,247261,39888,38023,22736,15287,7847,7441,1865
16,2003-2004,284367,245372,38995,37723,22551,15172,7842,7330,1272
17,2002-2003,282556,242463,40093,38824,23468,15356,7728,7628,1269
18,2001-2002,278160,237049,41111,39548,23712,15836,8066,7770,1563
19,2000-2001 (2000 controls)/3,275611,236605,39007,37251,21918,15333,7550,7783,1756
20,"2000-2001 (SCHIP, 2000 controls)/5",275611,235726,39885,38133,22774,15360,7778,7582,1752
21,2000-2001 (1990 controls)/6,272671,234029,38641,36993,21783,15210,7531,7679,1648
22,1999-2000,270219,226831,43388,41642,24399,17242,8814,8428,1746
23,1998-1999,267933,225297,42636,41207,25268,15939,8423,7516,1429
24,1997-1998,265209,222702,42507,41304,27082,14222,7867,6355,1203
25,1996-1997,262976,219585,43391,42088,27740,14348,7960,6389,1303
26,1995-1996,260406,217868,42537,41176,26696,14480,8009,6471,1361
27,1994-1995,258248,215931,42317,41539,27908,13631,7888,5743,778
28,1993-1994,255774,212939,42835,41590,26638,14952,8226,6726,1245
29,1992-1993 (1990 controls)/6,252799,209700,43099,41704,26932,14772,7855,6916,1395
...,...,...,...,...,...,...,...,...,...,...
106,1984-1985,100,79.8,20.2,19.6,13.1,6.5,3.5,3,0.6
107,1983-1984,100,82.7,17.3,16.8,10.4,6.4,3.6,2.8,0.5
108,1982-1983,100,83.4,16.6,16.1,10.1,6,3.3,2.7,0.4
109,1981-1982,100,83,17,16.6,10.3,6.2,3.3,3,0.5
110,1980-1981,100,82.8,17.2,16.6,10.4,6.2,3.4,2.8,0.6
111,1975-1976/8,100,82.3,17.7,17.1,10.8,6.4,3.4,3,0.6
112,1970-1971/8,100,81.3,18.7,17.9,11.4,6.5,3.1,3.4,0.8
113,1969-1970,100,80.9,19.1,18.4,11.7,6.7,3.1,3.6,0.8
114,1968-1969,100,81,19,18.3,11.7,6.6,3.2,3.4,0.7
115,1967-1968,100,80.5,19.5,18.8,11.8,7,3.4,3.6,0.7
116,1966-1967,100,81,19,18.3,11.6,6.7,3.3,3.4,0.7
117,1965-1966,100,80.2,19.8,19.3,12.7,6.6,3.3,3.3,0.5
118,1964-1965,100,79.3,20.7,20.1,13.4,6.8,3.5,3.3,0.5
119,1963-1964,100,79.9,20.1,19.6,13,6.6,3.3,3.3,0.5
120,1962-1963,100,80,20,19.4,12.6,6.8,3.1,3.6,0.6
121,1961-1962,100,80.4,19.6,19.1,13,6.1,3,3.1,0.5
122,1960-1961,100,79.4,20.6,20,13.7,6.3,3.1,3.2,0.6
123,1959-1960,100,80.1,19.9,19.4,12.9,6.4,3.3,3.2,0.5
124,1958-1959,100,80.3,19.7,19.2,13.1,6.1,3.2,3,0.5
125,1957-1958,100,79.7,20.3,19.8,13.1,6.7,3.4,3.3,0.5
126,1956-1957,100,80.1,19.9,19.4,13.1,6.2,3.2,3.1,0.5
127,1955-1956,100,78.9,21.1,20.5,13.7,6.8,3.6,3.1,0.6
128,1954-1955,100,79.6,20.4,19.9,13.3,6.6,3.5,3.1,0.6
129,1953-1954,100,80.7,19.3,18.6,12.2,6.4,3.2,3.2,0.6
130,1952-1953,100,79.4,20.6,20.1,13.5,6.6,3,3.6,0.5
131,1951-1952,100,79.7,20.3,19.8,13.2,6.6,3.2,3.4,0.4
132,1950-1951,100,78.8,21.2,21,13.9,7.1,3.6,3.5,0.2
133,1949-1950,100,80.9,19.1,18.7,13.1,5.6,3,2.6,0.3
134,1948-1949,100,80.8,19.2,18.8,13,5.8,2.8,3,0.3
135,1947-1948,100,79.8,20.2,19.9,13.6,6.4,3.3,3.1,0.3

- ***notes***:
    - table repeats time periods
- ***action***:
    - save this for later, focus on conversion of year ranges to years

In [12]:
# determine type of data in 'Mobility period' 
def test_type( dataframe , test_type ):
    '''
    input) dataframe w/ specified column 
        - e.g. df['specified column']
    input) type wanting to test
        - e.g. str 
    
    output) count of instances which are not type == test_type
    '''
    non_test_type = 0
    for _ in dataframe:
        if isinstance( _ , test_type ) == False:
            non_test_type += 1
    return non_test_type


test_000 = test_type( dataframe=df[ 'Mobility period' ] , test_type=str )
test_000

0

- ***as test_000 returns 0***:
    - the type of all datapoints in 'Mobility period' is str (string)
    - we will not need to change any points to have uniformity   
- ***next up (action)***:
    - clear low-hanging fruit
    - change the simple ranges to int for set year
        - e.g. change "2017-2018" to "2018"

In [13]:
# identify changes which can be implimented without further investigation
mobility_period = df[ 'Mobility period' ]
simple_year_ranges_count_ = 0
confirmed_simple_year_ranges_count_ = 0

# count how many simple-fix years we have
for datapoint in mobility_period:
    # len('2012-2013') == 9 , check datapoint is formatted as expected     
    if len( datapoint ) == 9 and len( datapoint.split( '-' ) ) == 2:
        # pretty sure we know what's going on but will investigate further         
        simple_year_ranges_count_ += 1
        # first 4 characters of string , can be converted to int
        first_year = int( datapoint[ :4 ] )
        # last 4 characters of string , can be converted to int
        second_year = int( datapoint[ -4: ] )
        # first_year and last_year are post-1940 (because expected), and year range is 1 year 
        if first_year and second_year > 1940 and second_year - first_year == 1:
            # the datapoint is within our risk threshold
            confirmed_simple_year_ranges_count_ += 1

# if everything we thought was what we think it is 
if simple_year_ranges_count_ == confirmed_simple_year_ranges_count_:
    print(f'total: {confirmed_simple_year_ranges_count_}\nratio: {confirmed_simple_year_ranges_count_/len(mobility_period)}')

total: 110
ratio: 0.8088235294117647

- ***notes***:
    - know count of lowest fruit to be 110 ( > 80.88% , not bad)
    - just confirmed status of 110 points to be (at least) similar enough to extract years
    - knowing simple_year_ranges_count_ allows the conformation of outcome via count compairson 
- ***action***:
    - convert those 110 year ranges to years represented by the 2nd year in each range

In [14]:
# set empty
less_low_mobility_periods = []
# row 0 == row 0
_ = -1

# little bit of ctrl + c , little bit of ctrl + v
for datapoint in mobility_period:
    _ += 1
    # len('2012-2013') == 9 , check datapoint is formatted as expected     
    if len( datapoint ) == 9 and len( datapoint.split( '-' ) ) == 2:
        # replace datapoint w/ int of last 4 characters of string 
        mobility_period[ _ ] = int( datapoint[ -4: ] )
    else:
        # keep what's already there
        less_low_mobility_periods.append( datapoint )

mobility_period #.sample(7)

0                                    2018
1                                    2017
2                                    2016
3                                    2015
4       2013-2014 (98,000 address file)/1
5                                    2013
6                                    2012
7             2010-2011 (2010 controls)/2
8             2010-2011 (2000 controls)/3
9             2009-2010 (2010 controls)/2
10            2009-2010 (2000 controls)/3
11                                   2009
12                                   2008
13                                   2007
14                                   2006
15                            2004-2005/4
16                                   2004
17                                   2003
18                                   2002
19            2000-2001 (2000 controls)/3
20     2000-2001 (SCHIP, 2000 controls)/5
21            2000-2001 (1990 controls)/6
22                                   2000
23                                   1999
24                                   1998
25                                   1997
26                                   1996
27                                   1995
28                                   1994
29            1992-1993 (1990 controls)/6
                      ...
106                                  1985
107                                  1984
108                                  1983
109                                  1982
110                                  1981
111                           1975-1976/8
112                           1970-1971/8
113                                  1970
114                                  1969
115                                  1968
116                                  1967
117                                  1966
118                                  1965
119                                  1964
120                                  1963
121                                  1962
122                                  1961
123                                  1960
124                                  1959
125                                  1958
126                                  1957
127                                  1956
128                                  1955
129                                  1954
130                                  1953
131                                  1952
132                                  1951
133                                  1950
134                                  1949
135                                  1948
Name: Mobility period, Length: 136, dtype: object

- ***notes***:
    - we have converted the low hanging fruit
- ***actions***:
    - now on to exploring the other 26 rows

In [15]:
# print them out , let's see what we can see
_ = 0
for row in df['Mobility period']:
    _ += 1    
    if not isinstance( row , int ):
        # _ check for consistent spacing
        if _ < 10:
            print( str(_) + '  |  ' + row )
        elif _ < 100:
            print( str(_) + ' |  ' + row )
        else:
            print( str(_) + '|  ' + row )

5  |  2013-2014 (98,000 address file)/1
8  |  2010-2011 (2010 controls)/2
9  |  2010-2011 (2000 controls)/3
10 |  2009-2010 (2010 controls)/2
11 |  2009-2010 (2000 controls)/3
16 |  2004-2005/4
20 |  2000-2001 (2000 controls)/3
21 |  2000-2001 (SCHIP, 2000 controls)/5
22 |  2000-2001 (1990 controls)/6
30 |  1992-1993 (1990 controls)/6
31 |  1992-1993 (1980 controls)/7
44 |  1975-1976/8
45 |  1970-1971/8
73 |  2013-2014 (98,000 address file)/1
76 |  2010-2011 (2010 controls)/2
77 |  2010-2011 (2000 controls)/3
78 |  2009-2010 (2010 controls)/2
79 |  2009-2010 (2000 controls)/3
84 |  2004-2005/4
88 |  2000-2001 (2000 controls)/3
89 |  2000-2001 (SCHIP, 2000 controls)/5
90 |  2000-2001 (1990 controls)/6
98 |  1992-1993 (1990 controls)/6
99 |  1992-1993 (1980 controls)/7
112|  1975-1976/8
113|  1970-1971/8

- ***notes***
    - 6 rows formatted almost like majority (new lowest)
        - all have either /4 or /8 at the end of otherwise standard string
            - e.g. standard 
                - 2004-2005
            - observation rows 
                - 16 |  2004-2005/4
                - 44 |  1975-1976/8
                - 45 |  1970-1971/8
                - 84 |  2004-2005/4
                - 112|  1975-1976/8
                - 113|  1970-1971/8
        - remarks before reading documentation
            - identical instances
                - rows 16 and 84
                - rows 44 and 112
                - rows 45 and 113
            - rows are not ordered by year
                - unless years reoccour/loop through table
                - or otherwise
    - 16 rows are in the next new lowest format
        - all contain ({year} controls)/{num} with year and num in consistent pairs
            - (year / num) pairs = # occurrences
                - (2010 / 2) = 4
                - (2000 / 3) = 6
                - (1990 / 6) = 4
                - (1980 / 7) = 2
        - they occour in pattern twice:
            - 4 uninterrupted
            - 1
            - 3 uninterrupted
        - sample rows
            - 8  |  2010-2011 (2010 controls)/2
            - 9  |  2010-2011 (2000 controls)/3
            - 10 |  2009-2010 (2010 controls)/2
            - 11 |  2009-2010 (2000 controls)/3
        - unknown analysis
            - seems to be game settings for different censuses 
            - difficult to connect the /2,/3 and /6,/7 relationship
                - if was dependent on decade order , possibles would be straight ordered 
                    - e.g. /2, /3, /4, /5 or /1, /3, /5, /7
                    
    - final 4 rows are longer and are 2 duplicate pairs
        - default format + ending either (98,000 address file)/1 or (SCHIP, 2000 controls)/5
            - longest rows
                - 5  |  2013-2014 (98,000 address file)/1
                - 21 |  2000-2001 (SCHIP, 2000 controls)/5
                - 73 |  2013-2014 (98,000 address file)/1
                - 89 |  2000-2001 (SCHIP, 2000 controls)/5
        - pre document remarks
            - first notice of /1 
            - return use of /5 
                - do other /n have additional possibile (paramaters)
    - blind analysis
        - year range
                - min: 1970-1971 (1971 in complete df)
                - max: 2013-2014 (2014 in complete df)
            - less range than full representation of column
                - min: 1948 (1947-1948 in origional df)
                - max: 2018 (2017-2018 in origional df)
            - why?
                - recent changes to census
                    - collection
                    - questions
                    - coverage
                - recent increase in census related surveys
                    - housing surveys
                    - business surveys
                        - we will be exploring these after fitting gen_000 model
                        - these are also how this data is presented for non-decade years
        - lot of possible meanings for non-conforming objects
                - politics..
                - changing standards
                - technological evolution
                - etc...
                    - storage , collection , methods , etc... 
            - full-court lobs
                - something to do with immigrants
                - evolution of process 
                - expansion of non-physical opportunities 
        - there's got to be a better way to extract dataframes from excel files
            - likely convertable, but annotations likely direct either universe to same result 
- ***actions***
    - go find out what these non-standard occurrences mean

In [16]:
# make another copy of origional dataframe (this is why we copy)
info_df = annual_geographical_mobility_rates_type_movement.copy()

# function to make NaN dataframe
row_nans = lambda df: df[ df.isnull().any( axis=1 ) ]

# identify the rows with information (basically, keep the NaNs this time)
nan_df = row_nans( info_df )

# peak some rows with NaN values 
nan_df.head()

,Table with row headers in column A and column headers in rows 5 through 7.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,"Table A-1. Annual Geographical Mobility Rates,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(Numbers in thousands.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mobility period,"Total, 1 year old and over",Same residence (non-movers),Total movers,Different residence in the United States,NaN,NaN,NaN,NaN,Movers from abroad
4,NaN,NaN,NaN,NaN,Total,Same county,Different county,NaN,NaN,NaN

In [17]:
# noted column 0 name 
column_names = []

# make it slightly educational
for _ in nan_df[ :0 ]:
    # each _ is a string
    if isinstance( _ , str ):
        # add the string to column_names
        column_names.append( _ )
        
# this is the education
print( f'len(nan_df[:0])=={ len( nan_df[ :0 ] ) }\ntype(nan_df[:0])=={ type( nan_df[ :0 ] ) }\n'
      # The economy, stupid. 
       f'len(column_names)=={ len( column_names ) }\ntype(column_names={ type( column_names ) }' )

len(nan_df[:0])==0
type(nan_df[:0])==<class 'pandas.core.frame.DataFrame'>
len(column_names)==10
type(column_names=<class 'list'>

In [18]:
# we can find row headers in column A
if column_names[0] != 'Table with row headers in column A and column headers in rows 5 through 7.':
    raise AssertionError('')

# function to return non-NaN rows 
non_nans = lambda df: df.dropna()

# identify non-NaN rows from column A (the first column)
column_a = non_nans( nan_df[ 'Table with row headers in column A and column headers in rows 5 through 7.' ] )

# let's see
column_a

0      Table A-1. Annual Geographical Mobility Rates,...
1                                (Numbers in thousands.)
3                                        Mobility period
6                                                 NUMBER
90                                               PERCENT
173                                           Footnotes:
174    1/ The 2014 CPS ASEC included redesigned quest...
175    2/ Population controls consistent with 2010 Ce...
176    3/ Population controls consistent with 2000 Ce...
177    4/ Caution should be used when comparing numbe...
178    5/ SCHIP sample: poulation controls consistent...
179    6/ Population controls consistent with 1990 Ce...
180    7/ Population controls consistent with 1980 Ce...
181    8/ The 1-year geographic mobility question was...
182    For more information on the transition from Ce...
183    Adjustments to Household Survey Population Est...
184       Population Estimates in January 2012 webpage\n
185    Source:  U.S. Census Bureau, Current Populatio...
Name: Table with row headers in column A and column headers in rows 5 through 7., dtype: object

In [19]:
# identify information of interest
indicators_of_interest = [ '1/' , '2/' , '3/' , '4/' , '5/' , '6/' , '7/' , '8/' ]

# make copy
copy_column_a = column_a.copy()

# return rows from copy_column_a which contain an indicator from indicators_of_interest
rows_of_interest = [ row for indicator in indicators_of_interest for row in copy_column_a if indicator in row ]

# examine the lowest (remember: /4 and /8)
for row in rows_of_interest:
    if '4/' in row or '8/' in row:
        print( row + '\n' )

4/ Caution should be used when comparing numbers/rates of movers within the same county and from a different county between the 1999-2000 to 2004-2005 period with other periods. A change in processing resulted in a shift in the distribution of movers for these years. For additional information, see the "Impact of Processing on CPS Interstate Migration Rates" note < http://www.census.gov/population/www/socdemo/CPSnote.pdf >.

8/ The 1-year geographic mobility question was not asked between 1972 through 1975 and 1977 to 1980. The first half of the decade (1971-1975) asked about migration since 1970 and the second half (1976-1980) since 1975. Therefore, only 1970-1971 and 1975-1976 ask a comparable 1-year question.

- ***notes***:
    - /4 is fairly easy to account for
        - basically they flipped the method of recording 
            - https://www.census.gov/population/www/socdemo/CPSnote.pdf 
            - from
                - group > geography
            - to 
                - geography > group
        - "Users of interstate migration data should be cautious of comparing rates from the 1999-2000 to 2004-5 period with other periods."
    - /8 is dissapointing due to prelim scanning of San Francisco 
        - will need to be remembered if one year are factored
        - also indicates 5-year question could be used 
            - would need to ensure other 5-year periods are/get sorted 
            
- ***actions***:
    - compare with neighbors to determine optimal implementation 
        - hedge repeats

In [20]:
# reset
sims = df['Mobility period']
_ = -1

for row in sims:
    # update row
    _ += 1
    # id indicators
    if '/4'  in str(row) or '/8' in str(row): 
        # ensure next is logical
        if _ < 2:
            raise Exception( 'f' )
        # print 2 before through 2 after
        print ( '\n\n\n\n' , sims[ _-2 : _+3 ] )

 13           2007
14           2006
15    2004-2005/4
16           2004
17           2003
Name: Mobility period, dtype: object




 41           1982
42           1981
43    1975-1976/8
44    1970-1971/8
45           1970
Name: Mobility period, dtype: object




 42           1981
43    1975-1976/8
44    1970-1971/8
45           1970
46           1969
Name: Mobility period, dtype: object




 81           2007
82           2006
83    2004-2005/4
84           2004
85           2003
Name: Mobility period, dtype: object




 109           1982
110           1981
111    1975-1976/8
112    1970-1971/8
113           1970
Name: Mobility period, dtype: object




 110           1981
111    1975-1976/8
112    1970-1971/8
113           1970
114           1969
Name: Mobility period, dtype: object

- ***notes***:
    - no /4 and /8 instances have duplicate year range  
    - we are reliant on both /4 and /8 instances (all)
    
- ***actions***:
    - continue examining other non-standard rows
    - add /4 and /8 to list for default conversion 
        - default conversion = note in new column & convert as if standard

In [21]:
# make copy of rows of interest
copy_rows_of_interest = rows_of_interest.copy()
# used: /4, /8 ; unused: 1/, /2, /3, /5, /6, /7

# examine the next lowest (remember: /2 and /3 ; largest set, size=16)
for row in copy_rows_of_interest:
    if '2/' in row or '3/' in row:
        print( row + '\n' )

2/ Population controls consistent with 2010 Census.

3/ Population controls consistent with 2000 Census.

- ***notes***:
    - requires conformation of duplicates but ideally move forward with 2010 controls 
        - values most recent measures
        - return for 2000 controls for comps if time
    - https://www.census.gov/content/dam/Census/programs-surveys/acs/guidance/2010_Change_Population_Controls.pdf 
- ***actions***:
    - confirm duplicates

In [22]:
# reset
sims_001 = df['Mobility period']

# for each instance in sims_001
for _ in range( len( sims_001 ) ):
    # if instance is string
    if isinstance( sims_001[ _ ] , str ):
        # and first 11 characters in that string are same as first 11 characters in str(next row)
            # e.g. 2010-2011 ( == 2010-2011 (
        if sims_001[ _ ][ :11 ] == str( sims_001[ _+1 ])[ :11 ]:
            # output the first row, then the second
            print( sims[ _ ], '\n', sims[ _+1 ], '\n' )

2010-2011 (2010 controls)/2
 2010-2011 (2000 controls)/3

2009-2010 (2010 controls)/2
 2009-2010 (2000 controls)/3

2000-2001 (2000 controls)/3
 2000-2001 (SCHIP, 2000 controls)/5

2000-2001 (SCHIP, 2000 controls)/5
 2000-2001 (1990 controls)/6

1992-1993 (1990 controls)/6
 1992-1993 (1980 controls)/7

2010-2011 (2010 controls)/2
 2010-2011 (2000 controls)/3

2009-2010 (2010 controls)/2
 2009-2010 (2000 controls)/3

2000-2001 (2000 controls)/3
 2000-2001 (SCHIP, 2000 controls)/5

2000-2001 (SCHIP, 2000 controls)/5
 2000-2001 (1990 controls)/6

1992-1993 (1990 controls)/6
 1992-1993 (1980 controls)/7

- ***notes***:
    - duplicate confirmed:
        - 2010-1011
        - 2009-2010
        - 1992-1993        
        - each duplicate repeated in line with table repeat...
    - duplicate *NOT* confirmed:
        - /2 or /3 dependent 
            - 2000-2001
                - 2000-2001 (2000 controls)/3 
                - 2000-2001 (SCHIP, 2000 controls)/5 
            - duplicate repeated in line with table repeat...
        - *NOT* /2 or /3 dependent
            - 2000-2001
                - 2000-2001 (SCHIP, 2000 controls)/5 
                - 2000-2001 (1990 controls)/6 
            - 1992-1993
                - 1992-1993 (1990 controls)/6 
                - 1992-1993 (1980 controls)/7 
            - each duplicate repeated in line with table repeat...
    - some of these contain /5
        - *but NONE* contain /1
- ***actions***:
    - re-check for duplicate year ranges between other /# 
        - always good practice
        - could lead to reconsideration of one(+) /#

In [23]:
## reset
sims_002 = df[ 'Mobility period' ]
_ = 0
# to remember what we've seen
storage = []

# let's see what we can see
for row in sims_002:
    # keep track of the row
    _ += 1 

    # if instance (row) is not int
    if not isinstance( row , int ):
        
        # add 2nd year in year range to storage
        storage.append( row[ 5:9 ] )
        
        # how many times have we seen that year
        s_c_ = str( storage.count( row[ 5:9 ] ) )
        
        # we only care if the year has been seen at least twice (inclusive) as all rows are seen twice
        if int( s_c_ ) >= 2:
            # print row number, 2nd year in year range, times 2nd year has been seen, entire row
            # account for row number when formatting
            if _ < 10:
                print( str( _ ) + '  |  ' + row[ 5:9 ] + '  |  ' + s_c_ + '  |  ' + row )
            elif _ < 100:
                print( str( _ ) + ' |  ' + row[ 5:9 ] + '  |  ' + s_c_ + '  |  ' + row )
            else:
                print( str( _ ) + '|  ' + row[ 5:9 ] + '  |  ' + s_c_ + '  |  ' + row )

9  |  2011  |  2  |  2010-2011 (2000 controls)/3
11 |  2010  |  2  |  2009-2010 (2000 controls)/3
21 |  2001  |  2  |  2000-2001 (SCHIP, 2000 controls)/5
22 |  2001  |  3  |  2000-2001 (1990 controls)/6
31 |  1993  |  2  |  1992-1993 (1980 controls)/7
73 |  2014  |  2  |  2013-2014 (98,000 address file)/1
76 |  2011  |  3  |  2010-2011 (2010 controls)/2
77 |  2011  |  4  |  2010-2011 (2000 controls)/3
78 |  2010  |  3  |  2009-2010 (2010 controls)/2
79 |  2010  |  4  |  2009-2010 (2000 controls)/3
84 |  2005  |  2  |  2004-2005/4
88 |  2001  |  4  |  2000-2001 (2000 controls)/3
89 |  2001  |  5  |  2000-2001 (SCHIP, 2000 controls)/5
90 |  2001  |  6  |  2000-2001 (1990 controls)/6
98 |  1993  |  3  |  1992-1993 (1990 controls)/6
99 |  1993  |  4  |  1992-1993 (1980 controls)/7
112|  1976  |  2  |  1975-1976/8
113|  1971  |  2  |  1970-1971/8

- ***notes***:
    - issue
        - no omnipresent control
            - pre-2000 have 1990 or 1980 controls
            - post-2000 have 2000 or 2010 controls 
            - 2000 has 2000, 1990 and SCHIP 2000 controls
    - solutions
        - compare everything to 2000 
        - identify differences between 80, 90, 00, SCHIP 00, and 10
    - 2013-2014 is standalone, no options
- ***actions***:
    - restate /2 and /3 with /5, /6 and /7
    - check for differences , document
    - determine which filters to move forward with

In [24]:
# make copy of rows of interest
copy2_rows_of_interest = rows_of_interest.copy()
# used: /2, /3, /4, /8 ; unused: 1/, /5, /6, /7

re_state_with = ['2/' , '3/' , '5/' , '6/', '7/']
# examine the next lowest (remember: /2 and /3 ; largest set, size=16)
for row in copy2_rows_of_interest:
    for filter in re_state_with:
        if filter in row:
            print( row + '\n' )

2/ Population controls consistent with 2010 Census.

3/ Population controls consistent with 2000 Census.

5/ SCHIP sample: poulation controls consistent with 2000 Census.

6/ Population controls consistent with 1990 Census.

7/ Population controls consistent with 1980 Census.

In [25]:
# copy current dataframe (annual_geographical_mobility_rates_type_movement)
df_copy = df.copy()

# list of rows without converted years (reminder: origional 2010-2011 converted 2011)
non_converted_years = [row for row in df_copy[ 'Mobility period' ] if isinstance( row , str ) ]

# filter for rows which are not yet converted in the 'Mobility period' column
n_c_y_df = df_copy.loc[ df_copy['Mobility period'].isin( non_converted_years ) ]

# visualize (%) differences between rows 
i_mobility_change = n_c_y_df.set_index('Mobility period').pct_change()
# note: 0.0101 = 1.01% ; first row will be NaN ; compare 2nd same year to 1st (e.g. 2011 vs 2011 not 2011 vs 2013)
i_mobility_change

,"Total, 1 year old and over",Same residence (non-movers),Total movers,Different residence in the United States,Same county,Different county,Same state,Different state,Movers from abroad
Mobility period,,,,,,,,,
"2013-2014 (98,000 address file)/1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-2011 (2010 controls)/2,-0.022484,-0.023065,-0.018021,-0.017222,-0.004523,-0.044006,-0.089668,0.019288,-0.043248
2010-2011 (2000 controls)/3,-0.002098,-0.002511,0.001056,0.001856,-0.000214,0.006401,0.007498,0.004836,-0.023985
2009-2010 (2010 controls)/2,-0.005252,-0.014817,0.067569,0.071819,0.110825,-0.013282,0.053281,-0.095417,-0.068998
2009-2010 (2000 controls)/3,-0.001148,-0.001677,0.002537,0.003703,0.004130,0.002654,0.004015,0.000694,-0.039594
2004-2005/4,-0.043076,-0.058175,0.062547,0.039050,-0.126110,0.445306,0.255118,0.720065,0.971459
2000-2001 (2000 controls)/3,-0.040178,-0.043096,-0.022087,-0.020304,-0.035978,0.003009,-0.037849,0.045962,-0.058445
"2000-2001 (SCHIP, 2000 controls)/5",0.000000,-0.003715,0.022509,0.023677,0.039055,0.001761,0.030199,-0.025826,-0.002278
2000-2001 (1990 controls)/6,-0.010667,-0.007199,-0.031190,-0.029895,-0.043515,-0.009766,-0.031756,0.012793,-0.059361
1992-1993 (1990 controls)/6,-0.072879,-0.103957,0.115370,0.127348,0.236377,-0.028797,0.043022,-0.099362,-0.153519
1992-1993 (1980 controls)/7,-0.010241,-0.007334,-0.024386,-0.023043,-0.026734,-0.016247,-0.015277,-0.017206,-0.064516
1975-1976/8,-0.168423,-0.177199,-0.124976,-0.125126,-0.145468,-0.088494,-0.081319,-0.096660,-0.120307
1970-1971/8,-0.031542,-0.043649,0.024787,0.014476,0.027635,-0.007776,-0.127920,0.131270,0.344948
"2013-2014 (98,000 address file)/1",-0.999504,-0.999460,-0.999695,-0.999690,-0.999670,-0.999726,-0.999661,-0.999784,-0.999741
2010-2011 (2010 controls)/2,0.000000,-0.001130,0.008696,0.000000,0.013158,-0.027778,-0.095238,0.066667,0.000000
2010-2011 (2000 controls)/3,0.000000,0.000000,0.000000,0.008929,0.000000,0.000000,0.052632,0.000000,0.000000
2009-2010 (2010 controls)/2,0.000000,-0.010181,0.077586,0.070796,0.116883,0.000000,0.050000,-0.125000,-0.250000
2009-2010 (2000 controls)/3,0.000000,0.000000,0.000000,0.008264,0.011628,0.000000,0.000000,0.000000,0.000000
2004-2005/4,0.000000,-0.016000,0.112000,0.081967,-0.091954,0.514286,0.285714,0.857143,1.000000
2000-2001 (2000 controls)/3,0.000000,-0.002933,0.018196,0.023923,0.006647,0.049675,0.014581,0.086118,0.061883
"2000-2001 (SCHIP, 2000 controls)/5",0.000000,-0.003715,0.022509,0.022308,0.039055,0.001761,0.030199,-0.025826,-0.002278
2000-2001 (1990 controls)/6,0.000000,0.003506,-0.020744,-0.018122,-0.033201,0.000911,-0.021316,0.023714,-0.049219
1992-1993 (1990 controls)/6,0.000000,-0.032953,0.199608,0.216195,0.339384,0.039771,0.122401,-0.041266,-0.007266
1992-1993 (1980 controls)/7,0.000000,0.002410,-0.011765,-0.012121,-0.018692,0.000000,0.000000,0.000000,-0.166667
1975-1976/8,0.000000,-0.010817,0.053571,0.049080,0.028571,0.103448,0.096774,0.111111,0.200000
1970-1971/8,0.000000,-0.012151,0.056497,0.046784,0.055556,0.015625,-0.088235,0.133333,0.333333

- ***what we are looking for***:
    - large % changes between same years (Mobility period(s)) due to controls
- ***notes***:
    - reset is after 'Mobility period' == 1970-1971/8
    - differences don't seem all too terrible 
- ***actions***:
    - asdf

In [26]:
# gather periods
periods = [ period[:9] for period in n_c_y_df[ 'Mobility period' ] ]
# periods = [ period for period in n_c_y_df[ 'Mobility period' ] ]

for period in periods:    
    a = n_c_y_df[n_c_y_df['Mobility period'].str.contains( period )].set_index( 'Mobility period' ).pct_change()

# compare 
def compare_mobility():
    for _ in range(len(periods)):
        a = str(n_c_y_df['Mobility period'][_:_+1])
        b = periods[_]
        q = a
        a = q[5:14]
        c = a==b
        if c:
            print( a ,' | ', b ,' | ', c )
        else:
            a = q[6:15]
            c = a==b
            if c:
                print( a ,' | ', b ,' | ', c )
            else:
                a = q[7:16]
                c = a==b
                if c:
                    print( a ,' | ', b ,' | ', c )
                else:
                    print( a ,' | ', b ,' | ', c ,' | ', q )

                
def true_true():
    q = str(n_c_y_df['Mobility period'][0:1])[5:14] == periods[0]
    w = str(n_c_y_df['Mobility period'][1:2])[5:14] == periods[1]
    return q,w
# true_true()

In [27]:
def og_comps(  show=True , only=False , proof=False , threshold=0.005 , count=False ):
    # set variable of index 
    iix = i_mobility_change.index
    
    # non-threshold-meeting instances
    nt=0
    # record instances that don't paired
    np=[]
    # record instances that pair
    ip=[]
    # count total 
    tc=0
    # count number of pairs
    pairs=0
    # instances of only positive threshold
    p=0
    # instances of only negative threshold
    n=0
    # instances of both positive and negative threshold
    b=0
    
    # for the length of the index -1 (last row unable to compare to next indexed row)
    for _ in range( len( iix ) - 1 ):
        # update total count
        tc+=1
        
        # year range (from 'Mobility period') for row at this index is same as row at next index
        if iix[ _ ][ :9 ] == iix[ _+1 ][ :9 ]:
            # we have a pair, so update count
            pairs+=1
            # add instance to list of instances which can pair
            ip.append( iix[ _ ] )
            # add paired instance to list of instances which can pair (not for count, do not mind duplicates)
            ip.append( iix[ _+1 ] )
            
            
            # determine how many of the changes are 0.5%+ and positive
            meets = i_mobility_change.iloc[ _+1 ] >= threshold
            # determine how many of the changes are 0.5%+ and negative
            n_meets = i_mobility_change.iloc[ _+1 ] <= -(threshold)

            # if we only want threshold instances 
            if only==True:
   
                # if at least one value meets positive threshold
                if meets.sum()>=1:
                    # check for negative threshold
                    if n_meets.sum()>=1:
                        # keep count of how many times this has happened
                        b+=1
                        # output heads up on exceeding both + and - with dual thresh count
                        if show:
                            print(f'*+-*  above&below={b} *+-*')
                    # no instnaces of negative threshold
                    else:
                        # update number of positive threshold only
                        p+=1
                        # output heads up on positive only threshold
                        if show:
                            print(f'+** above only={p} **+')
                
                # at least one value meets negative threshold && no values met the positive threshold 
                elif n_meets.sum()>=1:
                    # update number of negative threshold only
                    n+=1
                    # output heads up on negative only threshold
                    if show:
                        print(f'-**  below only={n} **-')
                
                # if not meeting positive or negative threshold
                else:
                    # update count of pairs failing to meet threshold
                    nt+=1
                
                # output: 'Mobility period' of top then bottom column, change values
                print( iix[ _ ] ,'\n', iix[ _+1 ] ,'\n', i_mobility_change.iloc[ _+1 ] ,
                      '\n', 'mean =',i_mobility_change.iloc[ _+1 ].mean(), '\n\n')
                
            # output 'Mobility period' of top row then of bottom
            # along with the percent change from top row to bottom for each column
            else:
                if show:
                    print( iix[ _ ] ,'\n', iix[ _+1 ] ,'\n', i_mobility_change.iloc[ _+1 ], '\n', 
                          'mean =',i_mobility_change.iloc[ _+1 ].mean() ,'\n\n')
        
        # if no pair (or; otherwise, bad measure) 
        else:
            # update list of non-pair instances
            np.append( iix[ _ ] )
            
            # if we ask for proof
            if proof==True:
                # output 'Mobility period' of row in question then for row below
                if show:
                    print( iix[ _ ], '\n' , iix[ _+1 ] ,'\n\n')
            # if we ask for simple proof
            elif proof=='simple':
                # output index and corresponding 'Mobility period'
                if show:
                    print( _ , ' | ', iix[ _ ],'\n\n' )
    
    # determine number of instances that were never paired
    np = [ i for i in np if i not in ip ]
    
    # if we request the counts
    if count:      
        # sum non-paired instances
        npi = 0
        for _p in np:
            if _p not in ip:
                npi+=1
        # sum total threshold hits 
        th = p + n + b
        # if looking for threshold only
        if only==True:
            # return how many times the threshold was hit
            return f'number_pairs={pairs}, met_threshold={th}, dont_meet={nt}, paired={len(ip)}, non_paired={npi}, total_count={tc}'
        else:
            # dont return met_threshold or dont_meet
            return f'number_pairs={pairs}, paired={len(ip)}, non_paired={npi}, total_count={tc}'
            

# let's see
og_comps(threshold=0.005,proof=True,count=True,show=True,only=True)

2013-2014 (98,000 address file)/1
 2010-2011 (2010 controls)/2


*+-*  above&below=1 *+-*
2010-2011 (2010 controls)/2
 2010-2011 (2000 controls)/3
 Total, 1 year old and over                 -0.002098
Same residence (non-movers)                -0.002511
Total movers                                0.001056
Different residence in the United States    0.001856
Same county                                -0.000214
Different county                            0.006401
Same state                                  0.007498
Different state                             0.004836
Movers from abroad                         -0.023985
Name: 2010-2011 (2000 controls)/3, dtype: float64
 mean = -0.000795772307127006


2010-2011 (2000 controls)/3
 2009-2010 (2010 controls)/2


-**  below only=1 **-
2009-2010 (2010 controls)/2
 2009-2010 (2000 controls)/3
 Total, 1 year old and over                 -0.001148
Same residence (non-movers)                -0.001677
Total movers                                0.002537
Different residence in the United States    0.003703
Same county                                 0.004130
Different county                            0.002654
Same state                                  0.004015
Different state                             0.000694
Movers from abroad                         -0.039594
Name: 2009-2010 (2000 controls)/3, dtype: float64
 mean = -0.002742969981138926


2009-2010 (2000 controls)/3
 2004-2005/4


2004-2005/4
 2000-2001 (2000 controls)/3


*+-*  above&below=2 *+-*
2000-2001 (2000 controls)/3
 2000-2001 (SCHIP, 2000 controls)/5
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                -0.003715
Total movers                                0.022509
Different residence in the United States    0.023677
Same county                                 0.039055
Different county                            0.001761
Same state                                  0.030199
Different state                            -0.025826
Movers from abroad                         -0.002278
Name: 2000-2001 (SCHIP, 2000 controls)/5, dtype: float64
 mean = 0.009486862757121664


*+-*  above&below=3 *+-*
2000-2001 (SCHIP, 2000 controls)/5
 2000-2001 (1990 controls)/6
 Total, 1 year old and over                 -0.010667
Same residence (non-movers)                -0.007199
Total movers                               -0.031190
Different residence in the United States   -0.029895
Same county                                -0.043515
Different county                           -0.009766
Same state                                 -0.031756
Different state                             0.012793
Movers from abroad                         -0.059361
Name: 2000-2001 (1990 controls)/6, dtype: float64
 mean = -0.023394994248859307


2000-2001 (1990 controls)/6
 1992-1993 (1990 controls)/6


-**  below only=2 **-
1992-1993 (1990 controls)/6
 1992-1993 (1980 controls)/7
 Total, 1 year old and over                 -0.010241
Same residence (non-movers)                -0.007334
Total movers                               -0.024386
Different residence in the United States   -0.023043
Same county                                -0.026734
Different county                           -0.016247
Same state                                 -0.015277
Different state                            -0.017206
Movers from abroad                         -0.064516
Name: 1992-1993 (1980 controls)/7, dtype: float64
 mean = -0.02277612730114504


1992-1993 (1980 controls)/7
 1975-1976/8


1975-1976/8
 1970-1971/8


1970-1971/8
 2013-2014 (98,000 address file)/1


2013-2014 (98,000 address file)/1
 2010-2011 (2010 controls)/2


+** above only=1 **+
2010-2011 (2010 controls)/2
 2010-2011 (2000 controls)/3
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                 0.000000
Total movers                                0.000000
Different residence in the United States    0.008929
Same county                                 0.000000
Different county                            0.000000
Same state                                  0.052632
Different state                             0.000000
Movers from abroad                          0.000000
Name: 2010-2011 (2000 controls)/3, dtype: float64
 mean = 0.0068400167084377754


2010-2011 (2000 controls)/3
 2009-2010 (2010 controls)/2


+** above only=2 **+
2009-2010 (2010 controls)/2
 2009-2010 (2000 controls)/3
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                 0.000000
Total movers                                0.000000
Different residence in the United States    0.008264
Same county                                 0.011628
Different county                            0.000000
Same state                                  0.000000
Different state                             0.000000
Movers from abroad                          0.000000
Name: 2009-2010 (2000 controls)/3, dtype: float64
 mean = 0.0022102633096290594


2009-2010 (2000 controls)/3
 2004-2005/4


2004-2005/4
 2000-2001 (2000 controls)/3


*+-*  above&below=4 *+-*
2000-2001 (2000 controls)/3
 2000-2001 (SCHIP, 2000 controls)/5
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                -0.003715
Total movers                                0.022509
Different residence in the United States    0.022308
Same county                                 0.039055
Different county                            0.001761
Same state                                  0.030199
Different state                            -0.025826
Movers from abroad                         -0.002278
Name: 2000-2001 (SCHIP, 2000 controls)/5, dtype: float64
 mean = 0.009334741561270085


*+-*  above&below=5 *+-*
2000-2001 (SCHIP, 2000 controls)/5
 2000-2001 (1990 controls)/6
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                 0.003506
Total movers                               -0.020744
Different residence in the United States   -0.018122
Same county                                -0.033201
Different county                            0.000911
Same state                                 -0.021316
Different state                             0.023714
Movers from abroad                         -0.049219
Name: 2000-2001 (1990 controls)/6, dtype: float64
 mean = -0.012719109926137154


2000-2001 (1990 controls)/6
 1992-1993 (1990 controls)/6


-**  below only=3 **-
1992-1993 (1990 controls)/6
 1992-1993 (1980 controls)/7
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                 0.002410
Total movers                               -0.011765
Different residence in the United States   -0.012121
Same county                                -0.018692
Different county                            0.000000
Same state                                  0.000000
Different state                             0.000000
Movers from abroad                         -0.166667
Name: 1992-1993 (1980 controls)/7, dtype: float64
 mean = -0.02298161498900681


1992-1993 (1980 controls)/7
 1975-1976/8


1975-1976/8
 1970-1971/8

'number_pairs=10, met_threshold=10, dont_meet=0, paired=20, non_paired=7, total_count=25'

- ***notes***:
    - 7 instances of changes greater than 0.5%
        - ***key***
            - |change| < 0.5%
                - likely not an influence control decision
                - not noted in this md
                - mentioned in conclusion of study 
            - 0.5% <= |change| < 1.0%
                - likely ok; needs to be considered moving forward, noted
            - 1.0% < |change| < 5.0% 
                - requires investigation && notation
            - |change| >= 5.0% 
                - requires thorough investigation && notation
            - 0.5%
                - all pairs meeting the 0.5% threshold also meet the 1.15% threshold
                    - 9 pairs hit 1.16% threshold
                    - 8 pairs hit 3.905% threshold 
                    - 6 pairs hit 3.959% threshold
                    - 5 pairs hit 4.0% threshold
                    - 4 pairs hit 5.0% threshold
                    - 3 paris hit 5.5% threshold
                    - 2 pairs hit 6% threshold
                    - 1 pair hits 16.666666666666664% threshold 
                        - 1992-1993 
                            - (1990 controls)/6 vs (1980 controls)/7 
                                - Movers from abroad >> -0.166667 >> 16.6667%
                - 0.5% was chosen because 1% seemed too high
                - many instances in these tables are measurements < 10,000 , some < 1,000
                    - while 1% is 1%
                        - losing 9 out of 900 or 9 out of 9,000 seems more impactful than 1,000 out of 100,000
                        - cities of 2,500,000 are (usually) not dependent on one business 
                        - areas of 250,000 may depend heavily on one business 
        - ***2 instances of only positive threshold being met***
            - 2010-2011 
                - (2010 controls)/2 vs (2000 controls)/3
                    - Different residence in the United States >> 0.008929 >> 0.8929%
                        - likely manageable 
                    - Same state >> 0.052632 >>  5.2632%
                        - **requires thorough investigation**
            - 2010-2011 
                - (2010 controls)/2 vs (2000 controls)/3
                    - Different residence in the United States >> 0.008264 >> 0.8264%
                        - likely manageable, 7.448% less than prior
                    - Same county >> 0.011628 >> 1.1628%
                        - requires investigation
        - ***3 instances of only negative threshold being met***
            - 2009-2010
                - (2010 controls)/2 vs (2000 controls)/3 
                    - Movers from abroad >> -0.039594 >> -3.9594%
                        - requires investigation
            - 1992-1993 
                - (1990 controls)/6 vs (1980 controls)/7 
                    - Total, 1 year old and over >> -0.010241 >> -1.0241%
                        - requires investigation
                    - Same residence (non-movers) >> -0.007334 >> -0.7334%
                        - likely managable
                    - Total movers >> -0.024386 >> -2.4386%
                        - requires investigation
                    - Different residence in the United States >> -0.023043 >> -2.3043%
                        - requires investigation
                    - Same county >> -0.026734 >> -2.6734%
                        - requires investigation
                    - Different county >> -0.016247 >> -1.6247%
                        - requires investigation
                    - Same state >> -0.015277 >> -1.5277%
                        - requires investigation
                    - Different state >> -0.017206 >> -1.7206%
                        - requires investigation
                    - Movers from abroad >> -0.064516 >> 6.4516%
                        - **requires thorough investigation**
            - 1992-1993 
                - (1990 controls)/6 vs (1980 controls)/7 
                    - Total movers >> -0.011765 >> -1.1765%
                        - requires investigation
                    - Different residence in the United States >> -0.012121 >> -1.2121%
                        - requires investigation
                    - Same county >> -0.018692 >> -1.8692%
                        - requires investigation
                    - Movers from abroad >> -0.166667 >> 16.6667%
                        - **requires thorough investigation**
        - ***5 instances of positive and negative thresholds being met***
            - 2010-2011 
                - (2010 controls)/2 vs (2000 controls)/3 
                    - Different county >> 0.006401 >> 0.6401%
                        - likely managable
                    - Same state >> 0.007498 >> 0.7498%
                        - likely managable
                    - Movers from abroad >> -0.023985 >> -2.3985%
                        - requires investigation
            - 2000-2001 
                - (2000 controls)/3 vs (SCHIP, 2000 controls)/5 
                    - Total movers >> 0.022509 >> 2.2509%
                        - requires investigation
                    - Different residence in the United States >> 0.023677 >> 2.3677%
                        - requires investigation
                    - Same county >> 0.039055 >> 3.9055%
                        - requires investigation
                    - Same state >> 0.030199 >> 3.0199%
                        - requires investigation
                    - Different state >> -0.025826 >> -2.5826%
                        - requires investigation
            - 2000-2001 
                - (SCHIP, 2000 controls)/5 vs (1990 controls)/6 
                    - Total, 1 year old and over >> -0.010667 >> -1.0667%
                        - requires investigation
                    - Total movers >> -0.031190 >> -3.1190%
                        - requires investigation
                    - Different residence in the United States >> -0.029895 >> -2.9895%
                        - requires investigation
                    - Same county >> -0.043515 >> -4.3515%
                        - requires investigation
                    - Same state >> -0.031756 >> -3.1756%
                        - requires investigation
                    - Different state >> 0.012793 >> 1.2793%
                        - requires investigation
                    - Movers from abroad >> -0.059361 >> -5.9361%
                        - **requires thorough investigation**
            - 2000-2001 
                - (2000 controls)/3 vs (SCHIP, 2000 controls)/5 
                    - Total movers >> 0.022509 >> 2.2509%
                        - requires investigation
                    - Different residence in the United States >> 0.022308
                        - requires investigation
                    - Same county >> 0.039055
                        - requires investigation
                    - Same state >> 0.030199
                        - requires investigation
                    - Different state >> -0.025826
                        - requires investigation
            - 2000-2001 
                - (SCHIP, 2000 controls)/5 vs (1990 controls)/6 
                    - Total movers >> -0.020744 >> -2.0744%
                        - requires investigation
                    - Different residence in the United States >> -0.018122 >> -1.8122%
                        - requires investigation
                    - Same county >> -0.033201 >> -3.3201%
                        - requires investigation
                    - Same state >> -0.021316
                        - requires investigation
                    - Different state >> 0.023714 >> 2.3714%
                        - requires investigation
                    - Movers from abroad >> -0.049219 >> -4.9219%
                        - requires investigation
- ***conclusions***:
    - unless the change is greater than 5%, we do not have time to care
- ***actions***:
    - reevaluate with threshold == 0.05
    - calculate in reverse
        - determine if 2010 to 2000 is different form 2000 to 2010 
            - will impact moving forward
                - current idea
                    - go with whichever filter results in less total change (avg all column changes for row)
                        - issues
                            - remembering to id the filter (controls) being used
                            - could be difficult to follow via general overview
                        - solns
                            - write well
                - alt ideas
                    - go with values between filters
                        - e.g. mean
                        - issues
                            - ignores controls
                            - could lead to future issues by avoiding task now
                    - pick filter with less overall change across all rows
                        - issues
                            - could affect one row drastically and result in less overall change
                            - no filter applies accross all rows
                    - pick filter based on year
                        - e.g. 2010 == 2010 controls, 2000 == 2000 controls
                            - issues
                                - no real issue if proven to be least impactful on numbers

In [28]:
og_comps(threshold=0.05,only=False,count=True, proof=True)

2013-2014 (98,000 address file)/1
 2010-2011 (2010 controls)/2


2010-2011 (2010 controls)/2
 2010-2011 (2000 controls)/3
 Total, 1 year old and over                 -0.002098
Same residence (non-movers)                -0.002511
Total movers                                0.001056
Different residence in the United States    0.001856
Same county                                -0.000214
Different county                            0.006401
Same state                                  0.007498
Different state                             0.004836
Movers from abroad                         -0.023985
Name: 2010-2011 (2000 controls)/3, dtype: float64
 mean = -0.000795772307127006


2010-2011 (2000 controls)/3
 2009-2010 (2010 controls)/2


2009-2010 (2010 controls)/2
 2009-2010 (2000 controls)/3
 Total, 1 year old and over                 -0.001148
Same residence (non-movers)                -0.001677
Total movers                                0.002537
Different residence in the United States    0.003703
Same county                                 0.004130
Different county                            0.002654
Same state                                  0.004015
Different state                             0.000694
Movers from abroad                         -0.039594
Name: 2009-2010 (2000 controls)/3, dtype: float64
 mean = -0.002742969981138926


2009-2010 (2000 controls)/3
 2004-2005/4


2004-2005/4
 2000-2001 (2000 controls)/3


2000-2001 (2000 controls)/3
 2000-2001 (SCHIP, 2000 controls)/5
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                -0.003715
Total movers                                0.022509
Different residence in the United States    0.023677
Same county                                 0.039055
Different county                            0.001761
Same state                                  0.030199
Different state                            -0.025826
Movers from abroad                         -0.002278
Name: 2000-2001 (SCHIP, 2000 controls)/5, dtype: float64
 mean = 0.009486862757121664


2000-2001 (SCHIP, 2000 controls)/5
 2000-2001 (1990 controls)/6
 Total, 1 year old and over                 -0.010667
Same residence (non-movers)                -0.007199
Total movers                               -0.031190
Different residence in the United States   -0.029895
Same county                                -0.043515
Different county                           -0.009766
Same state                                 -0.031756
Different state                             0.012793
Movers from abroad                         -0.059361
Name: 2000-2001 (1990 controls)/6, dtype: float64
 mean = -0.023394994248859307


2000-2001 (1990 controls)/6
 1992-1993 (1990 controls)/6


1992-1993 (1990 controls)/6
 1992-1993 (1980 controls)/7
 Total, 1 year old and over                 -0.010241
Same residence (non-movers)                -0.007334
Total movers                               -0.024386
Different residence in the United States   -0.023043
Same county                                -0.026734
Different county                           -0.016247
Same state                                 -0.015277
Different state                            -0.017206
Movers from abroad                         -0.064516
Name: 1992-1993 (1980 controls)/7, dtype: float64
 mean = -0.02277612730114504


1992-1993 (1980 controls)/7
 1975-1976/8


1975-1976/8
 1970-1971/8


1970-1971/8
 2013-2014 (98,000 address file)/1


2013-2014 (98,000 address file)/1
 2010-2011 (2010 controls)/2


2010-2011 (2010 controls)/2
 2010-2011 (2000 controls)/3
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                 0.000000
Total movers                                0.000000
Different residence in the United States    0.008929
Same county                                 0.000000
Different county                            0.000000
Same state                                  0.052632
Different state                             0.000000
Movers from abroad                          0.000000
Name: 2010-2011 (2000 controls)/3, dtype: float64
 mean = 0.0068400167084377754


2010-2011 (2000 controls)/3
 2009-2010 (2010 controls)/2


2009-2010 (2010 controls)/2
 2009-2010 (2000 controls)/3
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                 0.000000
Total movers                                0.000000
Different residence in the United States    0.008264
Same county                                 0.011628
Different county                            0.000000
Same state                                  0.000000
Different state                             0.000000
Movers from abroad                          0.000000
Name: 2009-2010 (2000 controls)/3, dtype: float64
 mean = 0.0022102633096290594


2009-2010 (2000 controls)/3
 2004-2005/4


2004-2005/4
 2000-2001 (2000 controls)/3


2000-2001 (2000 controls)/3
 2000-2001 (SCHIP, 2000 controls)/5
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                -0.003715
Total movers                                0.022509
Different residence in the United States    0.022308
Same county                                 0.039055
Different county                            0.001761
Same state                                  0.030199
Different state                            -0.025826
Movers from abroad                         -0.002278
Name: 2000-2001 (SCHIP, 2000 controls)/5, dtype: float64
 mean = 0.009334741561270085


2000-2001 (SCHIP, 2000 controls)/5
 2000-2001 (1990 controls)/6
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                 0.003506
Total movers                               -0.020744
Different residence in the United States   -0.018122
Same county                                -0.033201
Different county                            0.000911
Same state                                 -0.021316
Different state                             0.023714
Movers from abroad                         -0.049219
Name: 2000-2001 (1990 controls)/6, dtype: float64
 mean = -0.012719109926137154


2000-2001 (1990 controls)/6
 1992-1993 (1990 controls)/6


1992-1993 (1990 controls)/6
 1992-1993 (1980 controls)/7
 Total, 1 year old and over                  0.000000
Same residence (non-movers)                 0.002410
Total movers                               -0.011765
Different residence in the United States   -0.012121
Same county                                -0.018692
Different county                            0.000000
Same state                                  0.000000
Different state                             0.000000
Movers from abroad                         -0.166667
Name: 1992-1993 (1980 controls)/7, dtype: float64
 mean = -0.02298161498900681


1992-1993 (1980 controls)/7
 1975-1976/8


1975-1976/8
 1970-1971/8

'number_pairs=10, paired=20, non_paired=7, total_count=25'

- ***notes***:
    - negative
        - 3/4 (75%) of changes >= 5% are negative only
            - 2000-2001 , /5 vs /6
                - Movers from abroad >> -0.059361 >> -5.9361%
            - 1992-1993 , /6 vs /7
                - Movers from abroad >> -0.064516 >> -6.4516%
            - 1992-1993 , /6 vs /7
                - Movers from abroad >> -0.166667 >> -16.6667%
        - all 
            - occour in Movers from abroad
            - are changed > 1% (grand total ; e.g. x=0.0075 , y=0.0064) higher than 2nd highest change
            - have these columns negative w/ |change| > 1%
                - Total movers 
                - Different residence in the United States  
                - Same county                                
    - positive
        - 1/4 (25%) of changes >= 5% are positive only
            - 2010-2011 , /2 vs /3
            - Same state >> 0.052632 >> 5.2632%
        - only ONE other affected value
            - Different residence in the United States >> 0.008929 >> 0.8929%
                - Same state = 4.3703% (grand total) difference (589.450106394893% larger)
- **knowledge**:
    - when Total movers decrease, the following may as well
        - Different residence in the United States
        - Same county 
        - Movers from abroad
- ***actions***:
    - y2k filter != SCHIP
    - determine if we want more or less Movers from abroad
    - compare 2000-2001 (1990 controls)/6  to 2000-2001 (2000 controls)/3

In [29]:
# n_c_y_df.set_index('Mobility period').pct_change()
# i_mobility_change.iloc[6:9]

# copy dataframe
n_c_y_copy = n_c_y_df.copy()

# extract 2000-2001 rows
x = n_c_y_copy.iloc[ 6:9 ]

# drop SCHIP && set index
x = x.set_index( 'Mobility period' ).drop( '2000-2001 (SCHIP, 2000 controls)/5' )


def better_comps( data , key , proof=False , difference=False , calculations=False , match_recap=False , high_level=False ):
    '''
    inputs)
        > data
            >> dataframe
        > key
            >> column name to index on
        > proof
            >> if True, prints proof of findings
        > difference
            >> if True, prints winner of over_under
                >> over_under: 
                    >> if the absolute value of a straight value is less than the absolute value of the corresponding reverse value
                        >> subtract the absolute straight value from the absolute reverse value
                            >> and add the remainder to over_under
                    >> if the absolute value of a reverse value is less than the absolute value of the correcponding straight value
                        >> subtract the absolute reverse value from the absolute straight value
                            >> and subtract the remainder from over_under
        > calculations
            >> if True, prints compared min, max, and mean values 
        > high_level
            >> only see high level
            >> excludes all info except high_level from showing
    '''
    # copy data
    df = data.copy()
    # index data on {key}
    df = df.set_index( key )
    
    # times straight wins win_count and over_under
    straight_outright_wins = 0
    # times straight wins win_count but not over_under
    straight_win_count_wins = 0
    # times straight wins over_under but not win_count
    straight_over_under_wins = 0
    # times reverse wins win_count and over_under
    reverse_outright_wins = 0
    # times reverse wins win_count but not over_under
    reverse_win_count_wins = 0
    # times reverse wins over_under but not win_count
    reverse_over_under_wins = 0
    
    # iterate over the index values
    for _ in range( len( df.index ) - 1 ):
        
        # set instance
        instance = df.index[ _ ]
        # plus one
        instance_1 = df.index[ _ + 1 ]
        # if first 9 from current value are same as first 9 from next value
        if instance[:9] == instance_1[:9]:
            
            # make new dataframe only containing those rows
            one_on_one_df = df.copy()[_:_+2]
    
            # calculate change for straight
            straight_copy = one_on_one_df.pct_change()
            # and change for the flip
            reverse_copy = one_on_one_df.iloc[::-1].pct_change()

            # extract names form first rows
            s1n = straight_copy.iloc[0].name
            r1n = reverse_copy.iloc[0].name

            # tag 2nd rows
            s2 = straight_copy.iloc[1]
            r2 = reverse_copy.iloc[1]

            # extract names form 2nd rows
            s2n = s2.name
            r2n = r2.name
            
            # high_level excludes all info except high_level from showing
            if not high_level:
                # output the change information
                if proof:
                    print(f'{s1n} > {s2n}\nstraight\n{s2}\n')
                    print(f'{r1n} > {r2n}\nreverse\n{r2}\n')

            # string straight calculations
            s = f'min = {s2.min()}\nmax = {s2.max()}\nmin v max = {s2.min() - s2.max()}\nmean = {s2.mean()}'
            # list straight calculations
            s = s.split('\n')
            # string reverse calculations
            r = f'min = {r2.min()}\nmax = {r2.max()}\nmin v max = {r2.min() - r2.max()}\nmean = {r2.mean()}'
            # list reverse calculations
            r = r.split('\n')

            # track total amount won by (+straight -reverse)
            over_under = 0
            # track straight wins
            s_win = 0
            # track reverse wins
            r_win = 0
            
            # compare straight to reverse , value for value
            for i in range(len(s2)):
                
                # name of value
                n = s2[ i:i+1 ].index[0]
                # s value (float)
                sv = [ _ for _ in s2[ i:i+1]][0]
                # r value (float)
                rv = [_ for _ in r2[ i:i+1 ]][0]
                
                # determine which absolute value is closer to zero (0)
                closer = abs( sv ) < abs( rv )
                
                # output name , s value , r value , winner
                if closer == True:
                    # if we actually want this
                    if high_level==False:
                        # want proof
                        if proof:
                            print(f'{n}\ns = {sv}\nr = {rv}\nwinner = straight\n{rv-sv} less than reverse')
                    # add to over_under
                    a = abs(rv)-abs(sv)
                    if a < 0:
                        raise Exception(f'abs(rv)-abs(sv) < 0 ; { abs(rv)-abs(sv) } ; closer=={closer}')
                    over_under += a
                    # add to tally of straight wins
                    s_win += 1
                # sv is further away from 0 than rv
                elif closer == False:
                    if high_level==False:
                        # want proof
                        if proof:
                            print(f'{n}\ns = {sv}\nr = {rv}\nwinner = reverse\n{sv-rv} less than straight')
                    a = abs(sv)-abs(rv)
                    if a < 0:
                        raise Exception(f'abs(sv)-abs(rv) < 0 ; { abs(sv)-abs(rv) } ; closer=={closer}')
                    # subtract from over_under
                    over_under -= a
                    # add to tally of reverse winse
                    r_win += 1

            # high level info ONLY
            if high_level:
                if s_win > r_win:
                    if over_under > 0:
                        print(f'STRAIGHT WINS OUTRIGHT\n{s1n} >> {s2n}\nbetter than\n{r1n} >> {r2n}\n')
                        straight_outright_wins += 1
                    elif over_under < 0:
                        print(f'STRAIGHT wins win count (r={r_win} v s={s_win})\nbut REVERSE wins over_under ({over_under})\n{r1n} >> {r2n}\ninconclusive\n{s1n} >> {s2n}\n')
                        straight_win_count_wins += 1
                        reverse_over_under_wins += 1
                elif s_win < r_win:
                    if over_under < 0:
                        print(f'REVERSE WINS OUTRIGHT\n{r1n} >> {r2n}\nbetter than\n{s1n} >> {s2n}\n')
                        reverse_outright_wins += 1
                    elif over_under > 0:
                        print(f'REVERSE wins win count (r={r_win} v s={s_win})\nbut STRAIGHT wins over_under ({over_under})\n{r1n} >> {r2n}\ninconclusive\n{s1n} >> {s2n}\n')
                        reverse_win_count_wins += 1
                        straight_over_under_wins += 1
                else:
                    raise Exception(f'ERROR high_level ERROR s_win={s_win} r_win={r_win}')
            
            else:
                # determine who won more matchups
                if match_recap:
                    if s_win > r_win:
                        print(f'\nSTRAIGHT WINS\ntotal straight = {s_win}\ntotal reverse = {r_win}')
                    elif s_win < r_win:
                        print(f'\nREVERSE WINS\ntotal straight = {s_win}\ntotal reverse = {r_win}')
                    else:
                        raise Exception(f'TIE\ns_win = {s_win}\nr_win = {r_win}\nTIE')

                # determine who won over_under
                if difference: 
                    if over_under < 0:
                        print(f'REVERSE WINS\nover_under = {over_under}\n')
                    elif over_under > 0:
                        print(f'STRAIGHT WINS\nover_under = {over_under}\n')
                    elif over_under == 0:
                        raise Exception(f'TIE\nover_under = {over_under}\nTIE')

                # output calculations list vs list [min, max, mean] for compairson
                if calculations:
                    for n in range( len( s )):
                        s_larger = abs(float(s[ n ].split(' ').pop())) > abs(float(r[ n ].split(' ').pop()))
                        if s_larger == True:
                            print(f'st {s[ n ]}\nre {r[ n ]}\nstraight wins\n')
                        elif s_larger == False:
                            print(f'st {s[ n ]}\nre {r[ n ]}\nreverse wins\n')
    if high_level:
        print(f'straight_outright_wins = {straight_outright_wins}\nreverse_outright_wins = {reverse_outright_wins}\nstraight_win_count_wins = {straight_win_count_wins}\nreverse_win_count_wins = {reverse_win_count_wins}\nstraight_over_under_wins = {straight_over_under_wins}\nreverse_over_under_wins = {reverse_over_under_wins}')
        # tally up straight points
        straight_score = ( straight_outright_wins * 2 ) + straight_win_count_wins + straight_over_under_wins
        # tally up reverse points
        reverse_score = ( reverse_outright_wins * 2 ) + reverse_win_count_wins + reverse_over_under_wins
        # display scores
        print(f'straight_score = {straight_score}\nreverse_score = {reverse_score}')
        # return the winner
        if straight_score > reverse_score:
            return 'STRAIGHT IS CHAMPION'
        elif straight_score < reverse_score :
            return 'REVERSE IS CHAMPION'
        elif straight_score == reverse_score:
            return f'{straight_score} TIE {reverse_score}'

In [30]:
better_comps( data=n_c_y_df , key='Mobility period' , proof=False , difference=False , calculations=False , match_recap=True , high_level=True )

REVERSE wins win count (r=5 v s=4)
but STRAIGHT wins over_under (0.00047586336831018095)
2010-2011 (2000 controls)/3 >> 2010-2011 (2010 controls)/2
inconclusive
2010-2011 (2010 controls)/2 >> 2010-2011 (2000 controls)/3

REVERSE wins win count (r=6 v s=3)
but STRAIGHT wins over_under (0.0015758179797495941)
2009-2010 (2000 controls)/3 >> 2009-2010 (2010 controls)/2
inconclusive
2009-2010 (2010 controls)/2 >> 2009-2010 (2000 controls)/3

REVERSE WINS OUTRIGHT
2000-2001 (SCHIP, 2000 controls)/5 >> 2000-2001 (2000 controls)/3
better than
2000-2001 (2000 controls)/3 >> 2000-2001 (SCHIP, 2000 controls)/5

STRAIGHT WINS OUTRIGHT
2000-2001 (SCHIP, 2000 controls)/5 >> 2000-2001 (1990 controls)/6
better than
2000-2001 (1990 controls)/6 >> 2000-2001 (SCHIP, 2000 controls)/5

STRAIGHT WINS OUTRIGHT
1992-1993 (1990 controls)/6 >> 1992-1993 (1980 controls)/7
better than
1992-1993 (1980 controls)/7 >> 1992-1993 (1990 controls)/6

REVERSE WINS OUTRIGHT
2010-2011 (2000 controls)/3 >> 2010-2011 (2010 controls)/2
better than
2010-2011 (2010 controls)/2 >> 2010-2011 (2000 controls)/3

REVERSE WINS OUTRIGHT
2009-2010 (2000 controls)/3 >> 2009-2010 (2010 controls)/2
better than
2009-2010 (2010 controls)/2 >> 2009-2010 (2000 controls)/3

REVERSE WINS OUTRIGHT
2000-2001 (SCHIP, 2000 controls)/5 >> 2000-2001 (2000 controls)/3
better than
2000-2001 (2000 controls)/3 >> 2000-2001 (SCHIP, 2000 controls)/5

STRAIGHT WINS OUTRIGHT
2000-2001 (SCHIP, 2000 controls)/5 >> 2000-2001 (1990 controls)/6
better than
2000-2001 (1990 controls)/6 >> 2000-2001 (SCHIP, 2000 controls)/5

REVERSE wins win count (r=5 v s=4)
but STRAIGHT wins over_under (0.03397235374703844)
1992-1993 (1980 controls)/7 >> 1992-1993 (1990 controls)/6
inconclusive
1992-1993 (1990 controls)/6 >> 1992-1993 (1980 controls)/7

straight_outright_wins = 3
reverse_outright_wins = 4
straight_win_count_wins = 0
reverse_win_count_wins = 3
straight_over_under_wins = 3
reverse_over_under_wins = 0
straight_score = 9
reverse_score = 11

'REVERSE IS CHAMPION'

- ***notes***:
    - close call
    - further validates idea (covered further down in this notebook)
        - that when data is ratio (2nd half of df)
            - earlier (older) filters have less impact
        - but when data is gross numbers (1st half of df)
            - later (newer) filters have less impact
    - from 2000 control to 1990 control dominates from 1990 to 2000
- ***actions***:
    - don't think about it too much
    - use 2000 control over 1990 control

- 2000-2001 (2000 controls)/3 2000-2001 (SCHIP, 2000 controls)/5 
    - Total, 1 year old and over                  0.000000
    - Same residence (non-movers)                -0.003715
    - Total movers                                0.022509
    - Different residence in the United States    0.023677
    - Same county                                 0.039055
    - Different county                            0.001761
    - Same state                                  0.030199
    - Different state                            -0.025826
    - Movers from abroad                         -0.002278
    - Name: 2000-2001 (SCHIP, 2000 controls)/5, dtype: float64 
    - mean = 0.009486862757121664

In [31]:
def comps( df=n_c_y_df , i_key='Mobility period' ,  threshold=0.05, display='straight' , show_misses=True , indicate=False , proof=False  , count=True , output=True , means_only=False ):
    '''
    inputs)
        df 
            >> dataframe
        i_key 
            >> what to index df on
        threshold
            >> level of change required in at least one column for pair to be of interest
        show_misses 
            >> show paired instances failing to meet threshold
        indicate
            >> display count of + , - , or both instances above each instance
            >> include hit , miss rate in final output (if count==True)
        proof
            >> display proof that instances do not pair
            >> if 'simple' 
                >> only display current instance , do not show instance it failed to pair with 
        count
            >> return number of: pairs, paired instances, non paired instances, total instances
            >> if indicate==True
                >> include met_threshold and dont_meet (threshold) counts in final output
        output
            >> True (default), returns all outcomes in list 
                >> if Flase , prints all outcomes  
        mean_only
            >> False by default
                >> if True , returns mean values only
                    >> all other outputs canceled 
    '''
    
    # outcomes will be output within a list
    if output==True:
        # initialize output list
        out = []

    # copy dataframe
    df = df.copy()
    
    # non-threshold-meeting instances
    non_thresh=0
    # count total 
    total=0
    # count number of pairs
    pairs=0
    # instances of only positive threshold
    positive_only=0
    # instances of only negative threshold
    negative_only=0
    # instances of both positive and negative threshold
    pos_and_neg=0
    
    # record instances that don't paired
    non_pair=[]
    # record instances that pair
    ip=[]

    def do_right( q , to_do=output ):
        '''
        inputs
            >> takes in object {q}
            >> based on to_do
                >> prints q (False) 
                >> appends q out (True)
        '''
        # check out vs print
        if to_do==True:
            # will happen if output=True
            out.append( q )                    
        # we will not be using the output , check instance , print appropriately
        else:
            # tuple
            if isinstance( q , tuple ):
                # print each
                print( _ for _ in q )
            # string
            if isinstance( q , str ):
                print( q )
            else:
                raise Exception( f'ERROR to_do ERROR\ntype = { type( q )}' )
    
    # top row to bottom row
    if display=='straight':
        # index dataframe
        df = df.set_index( i_key )
        # indicate % change in dataframe
        df = df.pct_change()
        # set variable of index values
        year_index = df.index
    # bottom row to top row
    if display=='reverse':
        # index dataframe
        df = df.set_index( i_key )
        # reverse index of df
        df = df.iloc[::-1]
        # indicate % change in dataframe
        df = df.pct_change()
        # set variable of reversed index values
        year_index = df.index       
        
    # for the length of the index -1 (last row unable to compare to next indexed row)
    for _ in range( len( year_index ) - 1 ):
        # update total count
        total+=1
        
        # year range (from 'Mobility period') for row at this index is same as row at next index
        if year_index[ _ ][ :9 ] == year_index[ _+1 ][ :9 ]:
            # we have a pair, so update count
            pairs+=1
            # add instance to list of instances which can pair
            ip.append( year_index[ _ ] )
            # add paired instance to list of instances which can pair (not for count, do not mind duplicates)
            ip.append( year_index[ _+1 ] )
            
            # determine how many of the changes are 0.5%+ and positive
            meets = df.iloc[ _+1 ] >= threshold
            # determine how many of the changes are 0.5%+ and negative
            n_meets = df.iloc[ _+1 ] <= -(threshold)

            # if we want to paint out threshold instances and indicators
            if indicate==True:
   
                # if at least one value meets positive threshold
                if meets.sum()>=1:
                    # check for negative threshold
                    if n_meets.sum()>=1:
                        # keep count of how many times this has happened
                        pos_and_neg+=1
                        # output heads up on exceeding both + and - with dual thresh count
                        q = (f'*+-*  above&below = { pos_and_neg } *+-*')
                        # output
                        do_right( q )

                    # no instnaces of negative threshold
                    else:
                        # update number of positive threshold only
                        positive_only+=1
                        # output heads up on positive only threshold
                        q = (f'*+* above only = { positive_only } *+*')
                        # output
                        do_right( q )

                # at least one value meets negative threshold && no values met the positive threshold 
                elif n_meets.sum()>=1:
                    # update number of negative threshold only
                    negative_only+=1
                    # output heads up on negative only threshold
                    q = (f'*-*  below only = { negative_only } *-*')
                    # output
                    do_right( q )           
                # if not meeting positive or negative threshold
                else:
                    # update count of pairs failing to meet threshold
                    non_thresh+=1
                
                # asking for means only
                if means_only==True:
                    # output 'Mobility period' pair max change, min chage, mean change
                    q = ( f'{year_index[ _ ]}\n{year_index[ _+1 ]}\nmin = {df.iloc[ _+1 ].min()}\nmax = {df.iloc[ _+1 ].max()}\nmin v max = {df.iloc[ _+1 ].min() - df.iloc[ _+1 ].max()}\nmean = {df.iloc[ _+1 ].mean()}\n' )
                # 'regular' outcome
                else:
                    # output: 'Mobility period' of top then bottom column, change values, mean change
                    q = ( f'{year_index[ _ ]}\n{year_index[ _+1 ]}' ,'\n', df.iloc[ _+1 ] ,
                          '\n', 'mean =',df.iloc[ _+1 ].mean(), '\n')
                # output
                do_right( q )

            # output 'Mobility period' of top row then of bottom
            # along with the percent change from top row to bottom for each column
            else:
                # document pairs failing to meet/exceed threshold
                if show_misses==True:
                    #  show min/max/mean miss
                    if means_only==True:
                        # output 'Mobility period' pair max change, min chage, mean change
                        q = ( f'fail{year_index[ _ ]}\n{year_index[ _+1 ]}\nmin = {df.iloc[ _+1 ].min()}\nmax = {df.iloc[ _+1 ].max()}\nmin v max = {df.iloc[ _+1 ].min() - df.iloc[ _+1 ].max()}\nmean = {df.iloc[ _+1 ].mean()}\n' )
                    else:
                        # show 'regular' miss
                        q = ( f'{year_index[ _ ]}\n{year_index[ _+1 ]}\n', df.iloc[ _+1 ], '\n', 
                          'mean =',df.iloc[ _+1 ].mean() ,'\n')
                    # output
                    do_right( q )
        
        # if no pair (or; otherwise, bad measure) 
        else:
            
            # update list of non-pair instances
            non_pair.append( year_index[ _ ] )
            
            # if we ask for proof
            if proof==True:
                # output 'Mobility period' of row in question then for row below
                q = f'{year_index[ _ ]}\n{year_index[ _+1 ]}\n\n'
                # operate 
                do_right( q )

            # if we ask for simple proof
            elif proof=='simple':
                # output index and corresponding 'Mobility period'
                q = f'{_}  | {year_index[ _ ]}\n\n'
                # output
                do_right( q )
                
            else:
                if proof==False:
                    pass
    
    # determine number of instances that were never paired
    comped_non_pair = [ i for i in non_pair if i not in ip ]
    
    # if we request the counts
    if count:      
        # sum non-paired instances
        npi = len( comped_non_pair )
        # sum total threshold hits 
        sum_thresh_hits = positive_only + negative_only + pos_and_neg
        # if looking for threshold indicators
        if indicate==True:
            # return how many times the threshold was hit
            q = f'number_pairs={pairs}, met_threshold={sum_thresh_hits}, dont_meet={non_thresh}, paired={len(ip)}, non_paired={npi}, total_count={total}'
        else:
            # dont return met_threshold or dont_meet
            q = f'number_pairs={pairs}, paired={len(ip)}, non_paired={npi}, total_count={total}'
        # output
        do_right( q )
    # asking for one final output 
    if output==True:
        return out

In [32]:
# straight
s = comps( df=n_c_y_df , i_key='Mobility period' ,  threshold=0.05, display='straight' , show_misses=True , indicate=True , proof='simple'  , count=True , output=True , means_only=True  ) 
# reverse
r = comps( df=n_c_y_df , i_key='Mobility period' ,  threshold=0.05, display='reverse' , show_misses=True , indicate=True , proof='simple'  , count=True , output=True , means_only=True  )

- ***note***:
    - going to print out the min, max, min - max, and mean values for pairs
- ***action***:
    - compare controls , pick those with least variance
        - score system
            - +1 for having lower mean score if pair hit threshold
                - +1 additional if not hitting threshold
                    - highest scores win

In [33]:
for _ in range(len(r) - 1):
    nr = r[ (len(r)-1) - _ ]
    ns = s[ _ ]
# #     print(f'r{_}\n{nr}\ns{_}\n{ns}')
#     if len(ns) == len(nr):
#         for _ in range(len(ns))
# #         print(ns,nr)
    print(f'r{_}\n{nr}\ns{_}\n{ns}\n')

r0
number_pairs=10, met_threshold=5, dont_meet=5, paired=20, non_paired=7, total_count=25
s0
0  | 2013-2014 (98,000 address file)/1



r1
24  | 2010-2011 (2010 controls)/2


s1
2010-2011 (2010 controls)/2
2010-2011 (2000 controls)/3
min = -0.023985239852398532
max = 0.00749829584185413
min v max = -0.03148353569425266
mean = -0.000795772307127006


r2
2010-2011 (2000 controls)/3
2010-2011 (2010 controls)/2
min = -0.007442489851150258
max = 0.02457466918714557
min v max = -0.03201715903829583
mean = 0.0008762783656037406

s2
2  | 2010-2011 (2000 controls)/3



r3
22  | 2009-2010 (2010 controls)/2


s3
2009-2010 (2010 controls)/2
2009-2010 (2000 controls)/3
min = -0.039593908629441676
max = 0.004129679660362706
min v max = -0.04372358828980438
mean = -0.002742969981138926


r4
2009-2010 (2000 controls)/3
2009-2010 (2010 controls)/2
min = -0.004112695545220424
max = 0.04122621564482021
min v max = -0.04533891119004063
mean = 0.0029315333794658833

s4
4  | 2009-2010 (2000 controls)/3



r5
20  | 2004-2005/4


s5
5  | 2004-2005/4



r6
19  | 2000-2001 (2000 controls)/3


s6
2000-2001 (2000 controls)/3
2000-2001 (SCHIP, 2000 controls)/5
min = -0.025825517152768818
max = 0.03905465827174015
min v max = -0.06488017542450897
mean = 0.009486862757121664


r7
2000-2001 (SCHIP, 2000 controls)/5
2000-2001 (2000 controls)/3
min = -0.0375867217001844
max = 0.026510155631759513
min v max = -0.06409687733194391
mean = -0.009030964128171356

s7
*-*  below only = 1 *-*

r8
2000-2001 (1990 controls)/6
2000-2001 (SCHIP, 2000 controls)/5
min = -0.012631853105873114
max = 0.06310679611650483
min v max = -0.07573864922237794
mean = 0.024408080611869904

s8
2000-2001 (SCHIP, 2000 controls)/5
2000-2001 (1990 controls)/6
min = -0.05936073059360736
max = 0.012793458190450968
min v max = -0.07215418878405833
mean = -0.023394994248859307


r9
*+* above only = 4 *+*
s9
8  | 2000-2001 (1990 controls)/6



r10
16  | 1992-1993 (1990 controls)/6


s10
*-*  below only = 2 *-*

r11
1992-1993 (1980 controls)/7
1992-1993 (1990 controls)/6
min = 0.007388476282895073
max = 0.06896551724137923
min v max = -0.06157704095848415
mean = 0.023587628082516045

s11
1992-1993 (1990 controls)/6
1992-1993 (1980 controls)/7
min = -0.06451612903225812
max = -0.007334287076776302
min v max = -0.057181841955481816
mean = -0.02277612730114504


r12
*+* above only = 3 *+*
s12
10  | 1992-1993 (1980 controls)/7



r13
14  | 1975-1976/8


s13
11  | 1975-1976/8



r14
13  | 1970-1971/8


s14
12  | 1970-1971/8



r15
12  | 2013-2014 (98,000 address file)/1


s15
13  | 2013-2014 (98,000 address file)/1



r16
11  | 2010-2011 (2010 controls)/2


s16
*+* above only = 1 *+*

r17
2010-2011 (2000 controls)/3
2010-2011 (2010 controls)/2
min = -0.050000000000000044
max = 0.0
min v max = -0.050000000000000044
mean = -0.006538839724680451

s17
2010-2011 (2010 controls)/2
2010-2011 (2000 controls)/3
min = 0.0
max = 0.05263157894736836
min v max = -0.05263157894736836
mean = 0.0068400167084377754


r18
*-*  below only = 1 *-*
s18
15  | 2010-2011 (2000 controls)/3



r19
9  | 2009-2010 (2010 controls)/2


s19
2009-2010 (2010 controls)/2
2009-2010 (2000 controls)/3
min = 0.0
max = 0.011627906976744207
min v max = -0.011627906976744207
mean = 0.0022102633096290594


r20
2009-2010 (2000 controls)/3
2009-2010 (2010 controls)/2
min = -0.011494252873563204
max = 0.0
min v max = -0.011494252873563204
mean = -0.0021878860205598472

s20
17  | 2009-2010 (2000 controls)/3



r21
7  | 2004-2005/4


s21
18  | 2004-2005/4



r22
6  | 2000-2001 (2000 controls)/3


s22
2000-2001 (2000 controls)/3
2000-2001 (SCHIP, 2000 controls)/5
min = -0.025825517152768818
max = 0.03905465827174037
min v max = -0.06488017542450919
mean = 0.009334741561270085


r23
2000-2001 (SCHIP, 2000 controls)/5
2000-2001 (2000 controls)/3
min = -0.03758672170018462
max = 0.02651015563175929
min v max = -0.06409687733194391
mean = -0.008885604139530953

s23
2000-2001 (SCHIP, 2000 controls)/5
2000-2001 (1990 controls)/6
min = -0.04921854659877545
max = 0.02371362486413453
min v max = -0.07293217146290998
mean = -0.012719109926137154


r24
2000-2001 (1990 controls)/6
2000-2001 (SCHIP, 2000 controls)/5
min = -0.023164314988268098
max = 0.05176641427186679
min v max = -0.07493072926013489
mean = 0.013328957926135358

s24
21  | 2000-2001 (1990 controls)/6



r25
*+* above only = 2 *+*
s25
*-*  below only = 3 *-*

r26
3  | 1992-1993 (1990 controls)/6


s26
1992-1993 (1990 controls)/6
1992-1993 (1980 controls)/7
min = -0.16666666666666663
max = 0.002409638554216942
min v max = -0.16907630522088357
mean = -0.02298161498900681


r27
1992-1993 (1980 controls)/7
1992-1993 (1990 controls)/6
min = -0.0024038461538461453
max = 0.19999999999999996
min v max = -0.2024038461538461
mean = 0.02675760816098237

s27
23  | 1992-1993 (1980 controls)/7



r28
*+* above only = 1 *+*
s28
24  | 1975-1976/8



r29
1  | 1975-1976/8


s29
number_pairs=10, met_threshold=4, dont_meet=6, paired=20, non_paired=7, total_count=25

In [34]:
'''s1
2010-2011 (2010 controls)/2
2010-2011 (2000 controls)/3
min = -0.023985239852398532
max = 0.00749829584185413
min v max = -0.03148353569425266
mean = -0.000795772307127006

r2
2010-2011 (2000 controls)/3
2010-2011 (2010 controls)/2
min = -0.007442489851150258
max = 0.02457466918714557
min v max = -0.03201715903829583
mean = 0.0008762783656037406'''
# 2010 , 2




'''s3
2009-2010 (2010 controls)/2
2009-2010 (2000 controls)/3
min = -0.039593908629441676
max = 0.004129679660362706
min v max = -0.04372358828980438
mean = -0.002742969981138926

r4
2009-2010 (2000 controls)/3
2009-2010 (2010 controls)/2
min = -0.004112695545220424
max = 0.04122621564482021
min v max = -0.04533891119004063
mean = 0.0029315333794658833'''
# 2010 , 2 


'''s6
2000-2001 (2000 controls)/3
2000-2001 (SCHIP, 2000 controls)/5
min = -0.025825517152768818
max = 0.03905465827174015
min v max = -0.06488017542450897
mean = 0.009486862757121664

r7
2000-2001 (SCHIP, 2000 controls)/5
2000-2001 (2000 controls)/3
min = -0.0375867217001844
max = 0.026510155631759513
min v max = -0.06409687733194391
mean = -0.009030964128171356'''
# SCHIP, 2000 , 2 


'''r8
2000-2001 (1990 controls)/6
2000-2001 (SCHIP, 2000 controls)/5
min = -0.012631853105873114
max = 0.06310679611650483
min v max = -0.07573864922237794
mean = 0.024408080611869904

s8
2000-2001 (SCHIP, 2000 controls)/5
2000-2001 (1990 controls)/6
min = -0.05936073059360736
max = 0.012793458190450968
min v max = -0.07215418878405833
mean = -0.023394994248859307'''
# SCHIP, 2000 , 1


'''r11
1992-1993 (1980 controls)/7
1992-1993 (1990 controls)/6
min = 0.007388476282895073
max = 0.06896551724137923
min v max = -0.06157704095848415
mean = 0.023587628082516045

s11
1992-1993 (1990 controls)/6
1992-1993 (1980 controls)/7
min = -0.06451612903225812
max = -0.007334287076776302
min v max = -0.057181841955481816
mean = -0.02277612730114504'''
# 1990 , 1


'''r17
2010-2011 (2000 controls)/3
2010-2011 (2010 controls)/2
min = -0.050000000000000044
max = 0.0
min v max = -0.050000000000000044
mean = -0.006538839724680451

s17
2010-2011 (2010 controls)/2
2010-2011 (2000 controls)/3
min = 0.0
max = 0.05263157894736836
min v max = -0.05263157894736836
mean = 0.0068400167084377754
'''
# 2000 , 1 


'''s19
2009-2010 (2010 controls)/2
2009-2010 (2000 controls)/3
min = 0.0
max = 0.011627906976744207
min v max = -0.011627906976744207
mean = 0.0022102633096290594


r20
2009-2010 (2000 controls)/3
2009-2010 (2010 controls)/2
min = -0.011494252873563204
max = 0.0
min v max = -0.011494252873563204
mean = -0.0021878860205598472'''
# 2000 , 2


'''s22
2000-2001 (2000 controls)/3
2000-2001 (SCHIP, 2000 controls)/5
min = -0.025825517152768818
max = 0.03905465827174037
min v max = -0.06488017542450919
mean = 0.009334741561270085

r23
2000-2001 (SCHIP, 2000 controls)/5
2000-2001 (2000 controls)/3
min = -0.03758672170018462
max = 0.02651015563175929
min v max = -0.06409687733194391
mean = -0.008885604139530953'''
# SCHIP, 2000 , 1



'''s23
2000-2001 (SCHIP, 2000 controls)/5
2000-2001 (1990 controls)/6
min = -0.04921854659877545
max = 0.02371362486413453
min v max = -0.07293217146290998
mean = -0.012719109926137154


r24
2000-2001 (1990 controls)/6
2000-2001 (SCHIP, 2000 controls)/5
min = -0.023164314988268098
max = 0.05176641427186679
min v max = -0.07493072926013489
mean = 0.013328957926135358'''
# SCHIP, 2000 , 2


'''s26
1992-1993 (1990 controls)/6
1992-1993 (1980 controls)/7
min = -0.16666666666666663
max = 0.002409638554216942
min v max = -0.16907630522088357
mean = -0.02298161498900681


r27
1992-1993 (1980 controls)/7
1992-1993 (1990 controls)/6
min = -0.0024038461538461453
max = 0.19999999999999996
min v max = -0.2024038461538461
mean = 0.02675760816098237'''
# 1980 , 1

pass

- ***notes***:
    - see whiteboard_pics/point_controls
    - use consistent filter when using data
        - if available, always go with
            - (SCHIP, 2000 controls)/5
        - when not available
            - if only using top half of data (numbers)
                - (2010 controls)/2 > (2000 controls)/3
                - (1990 controls)/6 > (1980 controls)/7
            - if only using bottom half of data (ratios)
                - (2010 controls)/2 < (2000 controls)/3
                - (1990 controls)/6 < (1980 controls)/7
            - if using full data
                - (2010 controls)/2 > (2000 controls)/3
                - (1990 controls)/6 > (1980 controls)/7
        - full ranking 
            - (SCHIP, 2000 controls)/5  >  (2010 controls)/2  >  (2000 controls)/3  >  (1990 controls)/6  >  (1980 controls)/7
- ***actions***:
    - make functions to 
        - convert top half of df using newer controls 
        - convert bottom half of df using older controls

In [103]:
def convert_a1( a1 , use='top' ):
    '''
    input)
        > a1
            >> dataframe for conversion 
        > use
            >> how you wish to use the converted data
                > note
                    >> dataframe repeats 
                        > top half is gross numbers
                            >> e.g. 15	2011-2012 	304924 	268436 	36488 	35334 	23493 	11842 	6782 	5059 	1154
                        > bottom half is ratios
                            >> e.g. 156	 1960-1961 	100 	79.4 	20.6 	20 	13.7 	6.3 	3.1 	3.2 	0.6
                >> 'top' (default)
                    > converts and returns top half of dataframe
                >> 'bottom'
                    > converts and returns bottom half of dataframe
                >> 'full' (NOT YET LIVE)
                    > coming soon
    output)
        > converted dataframe , "ready for anything"
    
    how it works)
        > sort_columns
            >> takes dataframe
            >> sets column names
            >> burns remaining fluf 
        > organize_mobility_periods
            >> converts 'Mobility period' values 
                >> from assortment of strings
                    >> e.g. '2013-2014 (98,000 address file)/1'
                >> to uniform int years 
                    >> e.g. 2014
    '''
    
    # copy dataframe
    base_copy = a1.copy()
    
    def sort_columns( dataframe ):
        '''
        > takes dataframe
            >> makes a copy for editing
            >> drops blank columns
        >> extracts column names information from remaining
            >> sets column names
        >> burns remaining fluf 
            >> resets index
        >> returns modified dataframe (does NOT change origional df)
        '''
        # copy dataframe
        df = dataframe.copy()
        # drop columns with less than 2 non-NaN values
        df = df.dropna( thresh= ( 2 ) )
        
        # collect column names as pd series
        col_names_0to4_9 = df.iloc[ 0 ]
        # ^columns 0-4 and 9 , from row 0
        col_names_5to6 = df.iloc[ 1 ]
        # ^columns 5 & 6 , from row 1
        col_names7to8 = df.iloc[ 2 ]
        # ^columns 7 & 8 , from row 2

        # initialize list of column names 
        column_names = [ column_name for column_name in col_names_0to4_9 ]
        # ^because it is the base list , list is first row of column names

        # set index count to -1 so column 0 == column 0  
        _ = -1
        # replace items 5 and 6 in column_names with column names 5 and 6
        for column_name in col_names_5to6:
            _ += 1
            # column_name is string (nan instances = float) and name is not 'Total'   
            if isinstance( column_name , str ) and column_name != 'Total':
                # column_name is aligned to replace a nan         
                if str( column_names[ _ ] ) == 'nan':
                    # replace item in column_names with column_name             
                    column_names[ _ ] = column_name
        # 0 == 0
        _ = -1
        # replace items 7 and 8 in column_names with column names 7 and 8
        for column_name in col_names7to8:
            _ += 1
            # column_name is string (nan instances = float) and name is not 'Total'   
            if isinstance( column_name , str ) and column_name != 'Total':
                # column_name is aligned to replace a nan         
                if str( column_names[ _ ] ) == 'nan':
                    # replace item in column_names with column_name             
                    column_names[ _ ] = column_name

        # (re)set column names
        df.columns = column_names

        # drop rows used to extract column names
        df = df[3:]

        # reset dataframe index
        df = df.reset_index( drop=True ) 

        # let's see
        return df 
    
    # get formatted copy of base_copy
    formatted_copy = sort_columns( dataframe=base_copy )
    
    def organize_mobility_periods( dataframe , method ):
        '''
        inputs)
            > dataframe
                >> dataframe to be modified
                    > Table A-1. Annual Geographical Mobility Rates, By Type of Movement: 2018
                    > may take others
            > method
                >> 'top'
                    > converts top half of df 
                    > raw numbers
                >> 'bottom'
                    > converts bottom half of df 
                    > ratios
        output)
            > usable dataframe 
                >> indexed on 'Mobility period'
        function)
            > converts 'Mobility period' values 
                >> from assortment of strings
                    > e.g. '2013-2014 (98,000 address file)/1'
                >> to uniform int years 
                    > e.g. 2014
        '''
        # make copy
        df = dataframe.copy()
        # cut out our half
        if method=='top':
            df = df[ :int( len( df.index ) / 2 )]
            drop_filters = [ '/3' , '/7' ]
            hard_keeps = [ 'SCHIP' ]
        elif method=='bottom':
            df = df[ int( len( df.index ) / 2 ):] 
            drop_filters = [ '/2' ]
        
        # isolate 'Mobility period'
        mobility_periods = df['Mobility period']
        # set empty
        less_low_mobility_periods = []
        # row 0 == row 0
        _ = -1

        # little bit of ctrl + c , little bit of ctrl + v
        for datapoint in mobility_periods:
            _ += 1
            # looking for the simples (e.g. '2012-2013')     
            if len( datapoint ) == 9: 
                # check datapoint is formatted as expected 
                if len( datapoint.split( '-' ) ) == 2:
                    # replace datapoint w/ int of last 4 characters of string 
                    mobility_periods[ _ ] =  int( datapoint[ -4: ] )
        
        # execute the easy conversions 100% to give non-standard a map
        for _ in range(len(mobility_periods)):
            # set datapoint
            datapoint = mobility_periods[ _ ]
            
            # look for strings
            if isinstance( datapoint , str ):
                
                # straight up we're always keeping /8 because we have to, so..
                if '/8' in datapoint:
                    # double check 2nd year vs above 
                    if datapoint[ 5:9 ] != str(mobility_periods[ _-1 ])[ 5:9] :
                        # and above
                        if datapoint[ 5:9 ] != str(mobility_periods[ _+1 ])[ 5:9 ]:
                            # set the set
                            mobility_periods[ _ ] = int( datapoint[ 5:9 ])
                
                # compare dropable filters to that string
                for dropable in drop_filters:
                    if dropable in datapoint:
                        # drop it
                        mobility_periods[ _ ] = 0
                
                # compare keepable filters as well (see, we're nice)
                for keepable in hard_keeps:
                    if keepable in datapoint:
                        # check above cell for string
                        if isinstance( mobility_periods[ _ - 1 ], str ):
                            # 2nd year the same
                            if mobility_periods[ _ - 1 ][ 5:9 ] == datapoint[ 5:9 ]:
                                # well we're keeping the keepable.. so....
                                mobility_periods[ _ - 1 ] = 0
                        # check below cell for string
                        if isinstance( mobility_periods[ _ + 1 ], str ):
                            # 2nd year the same
                            if mobility_periods[ _ + 1 ][ 5:9 ] == datapoint[ 5:9 ]:
                                # well we're keeping the keepable.. so....
                                mobility_periods[ _ + 1 ] = 0
        
        for _ in range(len(mobility_periods)):
            # set datapoint
            datapoint = mobility_periods[ _ ]
            # next level is the slightly non-standard (e.g. 2004-2005/4)
            # make sure instance is not already an int and is a str (as expected)
            if not isinstance( datapoint , int ) and isinstance( datapoint , str ): 
                # check datapoint right length and is formatted as expected
                if len( datapoint.split( '-' ) ) == 2:
                # if len( datapoint ) == 11 and len( datapoint.split( '-' ) ) == 2:
                    # year above is not same as 2nd year in this range
                    if str(mobility_periods[ _ - 1 ])[ :4 ] != mobility_periods[ _ ][ 5:9 ]:
                        # and year below is not same as 2nd year in this range
                        if str(mobility_periods[ _ + 1 ])[ :4 ] != mobility_periods[ _ ][ 5:9 ]:
                            # and both the above and below rows are already converted int
                            if isinstance( mobility_periods[ _ + 1 ], int ) and isinstance( mobility_periods[ _ - 1 ], int ):
                                # this seems like a pretty necessary row, so let's go ahead and convert 
                                mobility_periods[ _ ] = int( mobility_periods[ _ ][ 5:9 ] )
                    
            

                    
        
        # replace old 'Mobility period' column with new 
        df['Mobility period'] = mobility_periods

        return df
    
    # set df
    df = organize_mobility_periods( dataframe=formatted_copy , method=use ) 
    # drop the years we changed to 0s due to multiple instances under different filters
    formatted_df = df[df['Mobility period'] != 0]
    
    return formatted_df

In [104]:
# Table A-1. Annual Geographical Mobility Rates, By Type of Movement: 2018
A_1 = pd.read_excel( '../../data/cps-historical-migration-geographic-mobility/tab-a-1.xls' )
y = convert_a1( A_1 )

# for _ in range(int(len(y)/2)):
#     print(y.iloc[_])

# y[int( len( y.index ) / 2 ):]
# for _ in y:
#     print(_)
# if len(y.unique()) != len(y):
#     raise Exception('yo')
    
# for _ in range(len(y)):
#     x = len(str(y[_]))
#     # if not isinstance(y[_],int):
#     if x < 10:
#         if _ < 10:
#             print( f'{_} | {x} | {y[_]}' )
#         else:
#             print( f'{_}| {x} | {y[_]}' )
#     else:
#         if _ < 10:
#             print( f'{_} | {x}| {y[_]}' )
#         else:
#             print( f'{_}| {x}| {y[_]}' )

# for _ in range(len(y)-1):
#     if y[_] == y[_+1]:
#         raise Exception(f'\n\n{_} , {y[_]} , {y[_+1]}\n\n')
# o = 0
# k = 0
# for _ in y:
#     if isinstance(_,int):
#         o+=1
#     else:
#         k+=1
    
y

,Mobility period,"Total, 1 year old and over",Same residence (non-movers),Total movers,Different residence in the United States,Same county,Different county,Same state,Different state,Movers from abroad
0,2018,319319,286967,32352,31186,19852,11334,6496,4838,1165
1,2017,316550,281647,34902,33647,21614,12033,6668,5366,1255
2,2016,314992,279854,35138,33857,21588,12269,7501,4768,1281
3,2015,312295,275971,36324,34651,22905,11746,6653,5093,1673
4,2014,309601,273920,35681,34548,23436,11112,6446,4666,1133
5,2013,307243,271325,35918,34882,23150,11731,6961,4770,1036
6,2012,304924,268436,36488,35334,23493,11842,6782,5059,1154
7,2011,302640,267602,35038,33953,23330,10623,5868,4756,1084
9,2010,300419,262975,37445,36459,25910,10549,6227,4323,985
11,2009,297182,260077,37105,36017,24984,11034,6374,4660,1087
12,2008,294851,259685,35167,34022,23013,11009,6282,4728,1145
13,2007,292749,254068,38681,37490,25192,12298,7436,4862,1191
14,2006,289781,249945,39837,38541,24851,13690,8010,5679,1296
15,2005,287148,247261,39888,38023,22736,15287,7847,7441,1865
16,2004,284367,245372,38995,37723,22551,15172,7842,7330,1272
17,2003,282556,242463,40093,38824,23468,15356,7728,7628,1269
18,2002,278160,237049,41111,39548,23712,15836,8066,7770,1563
20,2001,275611,235726,39885,38133,22774,15360,7778,7582,1752
22,2000,270219,226831,43388,41642,24399,17242,8814,8428,1746
23,1999,267933,225297,42636,41207,25268,15939,8423,7516,1429
24,1998,265209,222702,42507,41304,27082,14222,7867,6355,1203
25,1997,262976,219585,43391,42088,27740,14348,7960,6389,1303
26,1996,260406,217868,42537,41176,26696,14480,8009,6471,1361
27,1995,258248,215931,42317,41539,27908,13631,7888,5743,778
28,1994,255774,212939,42835,41590,26638,14952,8226,6726,1245
29,1993,252799,209700,43099,41704,26932,14772,7855,6916,1395
31,1992,247380,204580,42800,41545,26587,14957,7853,7105,1255
32,1991,244884,203345,41539,40154,25151,15003,7881,7122,1385
33,1990,242208,198827,43381,41821,25726,16094,8061,8033,1560
34,1989,239793,197173,42620,41153,26123,15030,7949,7081,1467
...,...,...,...,...,...,...,...,...,...,...
38,1985,230333,183863,46470,45043,30126,14917,7995,6921,1427
39,1984,228232,188853,39379,38300,23659,14641,8198,6444,1079
40,1983,225874,188465,37408,36430,22858,13572,7403,6169,978
41,1982,223719,185592,38127,37039,23081,13959,7330,6628,1088
42,1981,221641,183442,38200,36887,23097,13789,7614,6175,1313
43,1976,208069,171276,36793,35645,22399,13246,7106,6140,1148
44,1971,201506,163800,37705,36161,23018,13143,6197,6946,1544
45,1970,198955,160860,38095,36541,23225,13316,6250,7066,1554
46,1969,196642,159310,37332,35933,22993,12940,6316,6625,1399
47,1968,194621,156735,37886,36603,22960,13643,6607,7035,1283
48,1967,192233,155710,36523,35200,22339,12861,6308,6553,1323
49,1966,190242,152656,37586,36703,24165,12538,6275,6263,883
50,1965,187974,149128,38846,37866,25122,12744,6597,6147,978
51,1964,185312,148125,37187,36327,24089,12238,6191,6047,859
52,1963,182541,146109,36432,35411,23059,12352,5712,6640,1021
53,1962,179663,144445,35218,34364,23341,11023,5461,5562,854
54,1961,177354,140821,36533,35535,24289,11246,5493,5753,998
55,1960,174451,139766,34685,33811,22564,11247,5724,5523,874
56,1959,170658,137018,33640,32804,22315,10489,5419,5070,836
57,1958,167604,133501,34103,33263,22023,11240,5656,5584,840
58,1957,164371,131648,32723,31834,21566,10268,5192,5076,889
59,1956,161497,127457,34040,33098,22186,10912,5859,5053,942
60,1955,158609,126190,32419,31492,21086,10406,5511,4895,927
61,1954,155679,125654,30025,29027,19046,9981,4947,5034,998
62,1953,153038,121512,31526,30786,20638,10148,4626,5522,740
63,1952,150494,120016,30478,29840,19874,9966,4854,5112,638
64,1951,148400,116936,31464,31158,20694,10464,5276,5188,306
65,1950,146864,118849,28015,27526,19276,8250,4360,3889,491
66,1949,144101,116498,27603,27127,18792,8335,3992,4344,476
67,1948,141698,113026,28672,28210,19202,9008,4638,4370,462

In [45]:
qq =  annual_geographical_mobility_rates_type_movement.copy()
c_qq = convert_a1(qq.copy())

In [46]:
qq = []
for _ in c_qq['Mobility period']:
    qq.append(_)

In [107]:
len(qq)/2

68.0

In [48]:
a = convert_a1(A_1)
a = a['Mobility period']
a = a[:int(len(a)/2)]

In [50]:
for _ in range(len(y)):
    pass
#     print(f'{a[_]}\n{y[_]}\n')

In [51]:
"""
    class OrganizeMobilityPeriods(  , method ):
        '''
        inputs)
            > dataframe
                >> dataframe to be modified
                    > Table A-1. Annual Geographical Mobility Rates, By Type of Movement: 2018
                    > may take others
            > method
                >> 'top'
                    > converts top half of df 
                    > raw numbers
                >> 'bottom'
                    > converts bottom half of df 
                    > ratios
        output)
            > usable dataframe 
                >> indexed on 'Mobility period'
        function)
            > converts 'Mobility period' values 
                >> from assortment of strings
                    > e.g. '2013-2014 (98,000 address file)/1'
                >> to uniform int years 
                    > e.g. 2014
        '''
        def __init__( self , dataframe ):
            # df
            self.dataframe = dataframe

        # make copy
        df = self.dataframe.copy()
        
        # set empty
        less_low_mobility_periods = []
        # row 0 == row 0
        _ = -1

        # little bit of ctrl + c , little bit of ctrl + v
        for datapoint in mobility_period:
            _ += 1
            # len('2012-2013') == 9 , check datapoint is formatted as expected     
            if len( datapoint ) == 9 and len( datapoint.split( '-' ) ) == 2:
                # replace datapoint w/ int of last 4 characters of string 
                mobility_period[ _ ] = int( datapoint[ -4: ] )
            else:
                # keep what's already there
                less_low_mobility_periods.append( datapoint )

        return mobility_period 
"""
pass

In [52]:
A_1 = pd.read_excel( '../../data/cps-historical-migration-geographic-mobility/tab-a-1.xls' )
A_1

,Table with row headers in column A and column headers in rows 5 through 7.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,"Table A-1. Annual Geographical Mobility Rates,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(Numbers in thousands.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mobility period,"Total, 1 year old and over",Same residence (non-movers),Total movers,Different residence in the United States,NaN,NaN,NaN,NaN,Movers from abroad
4,NaN,NaN,NaN,NaN,Total,Same county,Different county,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,Total,Same state,Different state,NaN
6,NUMBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2017-2018,319319,286967,32352,31186,19852,11334,6496,4838,1165
9,2016-2017,316550,281647,34902,33647,21614,12033,6668,5366,1255
10,2015-2016,314992,279854,35138,33857,21588,12269,7501,4768,1281
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2014-2015,312295,275971,36324,34651,22905,11746,6653,5093,1673
13,"2013-2014 (98,000 address file)/1",309601,273920,35681,34548,23436,11112,6446,4666,1133
14,2012-2013,307243,271325,35918,34882,23150,11731,6961,4770,1036
15,2011-2012,304924,268436,36488,35334,23493,11842,6782,5059,1154
16,2010-2011 (2010 controls)/2,302640,267602,35038,33953,23330,10623,5868,4756,1084
17,2010-2011 (2000 controls)/3,302005,266930,35075,34016,23325,10691,5912,4779,1058
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2009-2010 (2010 controls)/2,300419,262975,37445,36459,25910,10549,6227,4323,985
20,2009-2010 (2000 controls)/3,300074,262534,37540,36594,26017,10577,6252,4326,946
21,2008-2009,297182,260077,37105,36017,24984,11034,6374,4660,1087
22,2007-2008,294851,259685,35167,34022,23013,11009,6282,4728,1145
23,2006-2007,292749,254068,38681,37490,25192,12298,7436,4862,1191
24,2005-2006,289781,249945,39837,38541,24851,13690,8010,5679,1296
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2004-2005/4,287148,247261,39888,38023,22736,15287,7847,7441,1865
27,2003-2004,284367,245372,38995,37723,22551,15172,7842,7330,1272
28,2002-2003,282556,242463,40093,38824,23468,15356,7728,7628,1269
29,2001-2002,278160,237049,41111,39548,23712,15836,8066,7770,1563
...,...,...,...,...,...,...,...,...,...,...
156,1960-1961,100,79.4,20.6,20,13.7,6.3,3.1,3.2,0.6
157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,1959-1960,100,80.1,19.9,19.4,12.9,6.4,3.3,3.2,0.5
159,1958-1959,100,80.3,19.7,19.2,13.1,6.1,3.2,3,0.5
160,1957-1958,100,79.7,20.3,19.8,13.1,6.7,3.4,3.3,0.5
161,1956-1957,100,80.1,19.9,19.4,13.1,6.2,3.2,3.1,0.5
162,1955-1956,100,78.9,21.1,20.5,13.7,6.8,3.6,3.1,0.6
163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,1954-1955,100,79.6,20.4,19.9,13.3,6.6,3.5,3.1,0.6
165,1953-1954,100,80.7,19.3,18.6,12.2,6.4,3.2,3.2,0.6
166,1952-1953,100,79.4,20.6,20.1,13.5,6.6,3,3.6,0.5
167,1951-1952,100,79.7,20.3,19.8,13.2,6.6,3.2,3.4,0.4
168,1950-1951,100,78.8,21.2,21,13.9,7.1,3.6,3.5,0.2
169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,1949-1950,100,80.9,19.1,18.7,13.1,5.6,3,2.6,0.3
171,1948-1949,100,80.8,19.2,18.8,13,5.8,2.8,3,0.3
172,1947-1948,100,79.8,20.2,19.9,13.6,6.4,3.3,3.1,0.3
173,Footnotes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,1/ The 2014 CPS ASEC included redesigned quest...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,2/ Population controls consistent with 2010 Ce...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,3/ Population controls consistent with 2000 Ce...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,4/ Caution should be used when comparing numbe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,5/ SCHIP sample: poulation controls consistent...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,6/ Population controls consistent with 1990 Ce...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,7/ Population controls consistent with 1980 Ce...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,8/ The 1-year geographic mobility question was...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,For more information on the transition from Ce...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,Adjustments to Household Survey Population Est...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,Population Estimates in January 2012 webpage\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,"Source: U.S. Census Bureau, Current Populatio...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
'2004-2005/4PASTA '[5:9]

'2005'